In [48]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
import statistics

In [61]:
df1 = pd.read_csv('climatetrace.csv')
df2 = pd.read_csv('WorldBank.csv')
df3 = pd.read_excel('LMOP.xlsx')
df4 = pd.read_csv('waste_atlas_dumpsites.csv')
df5 = pd.read_csv('waste_atlas_landfills.csv')
df6 = pd.read_excel('MSW_AsiaPacific1.xlsx')
df7 = pd.read_excel('LMOP_full.xlsx')

In [120]:
#This is just emissions data, no waste
#23725 rows × 20 columns
df1.head()

,asset_id,iso3_country,original_inventory_sector,start_time,end_time,temporal_granularity,gas,emissions_quantity,emissions_factor,emissions_factor_units,capacity,capacity_units,capacity_factor,activity,activity_units,created_date,modified_date,asset_name,asset_type,st_astext
0,1835960681,KOR,solid-waste-disposal,2021-01-01 00:00:00,2021-12-31 00:00:00,annual,co2,NaN,NaN,NaN,114486480.5,landfill_area_sq_meters,NaN,6582168.267,estimated_tonnes_waste_in_place,2023-01-24 00:00:00,NaN,Sudokwon,Sanitary Landfills,POINT(126.613998413085 37.5772357911111)
1,1835960681,KOR,solid-waste-disposal,2021-01-01 00:00:00,2021-12-31 00:00:00,annual,ch4,2.280719e+05,0.03465,NaN,114486480.5,landfill_area_sq_meters,NaN,6582168.267,estimated_tonnes_waste_in_place,2023-01-24 00:00:00,NaN,Sudokwon,Sanitary Landfills,POINT(126.613998413085 37.5772357911111)
2,1835960681,KOR,solid-waste-disposal,2021-01-01 00:00:00,2021-12-31 00:00:00,annual,n2o,NaN,NaN,NaN,114486480.5,landfill_area_sq_meters,NaN,6582168.267,estimated_tonnes_waste_in_place,2023-01-24 00:00:00,NaN,Sudokwon,Sanitary Landfills,POINT(126.613998413085 37.5772357911111)
3,1835960681,KOR,solid-waste-disposal,2021-01-01 00:00:00,2021-12-31 00:00:00,annual,co2e_100yr,6.386013e+06,NaN,NaN,114486480.5,landfill_area_sq_meters,NaN,6582168.267,estimated_tonnes_waste_in_place,2023-01-24 00:00:00,NaN,Sudokwon,Sanitary Landfills,POINT(126.613998413085 37.5772357911111)
4,1835960681,KOR,solid-waste-disposal,2021-01-01 00:00:00,2021-12-31 00:00:00,annual,co2e_20yr,1.915804e+07,NaN,NaN,114486480.5,landfill_area_sq_meters,NaN,6582168.267,estimated_tonnes_waste_in_place,2023-01-24 00:00:00,NaN,Sudokwon,Sanitary Landfills,POINT(126.613998413085 37.5772357911111)

In [20]:
# This is just waste data, no emissions
#329 rows × 28 columns
df2.head()

,iso3c,region_id,country_name,income_id,city_name,population_population_number_of_people,primary_collection_mode_form_of_primary_collection_na,total_msw_total_msw_generated_tons_year,composition_food_organic_waste_percent,composition_glass_percent,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,AFG,SAS,Afghanistan,LIC,Jalalabad,326585,Door-to-door collection,58914.45,1.0455,1.1175,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,Kandahar,429000,Centralized drop-off point,120971,11.6000,2.3110,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,635250,Centralized drop-off point,52368.4,50.5000,1.3200,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN
3,AFG,SAS,Afghanistan,LIC,Kabul,3700000,Centralized drop-off point,1989250,13.5000,1.0000,...,NaN,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,25.0
4,AFG,SAS,Afghanistan,LIC,Hirat√Ç¬†,337000,Door-to-door collection,91644.7,52.9400,1.4700,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN

In [5]:
# This is just emissions data, no waste
#81290 rows × 12 columns
df3.head()

,Facility Id,Facility Name,City,State,Zip Code,Address,County,Latitude,Longitude,Industry Type (sectors),emissions,Year
0,1004377,121 REGIONAL DISPOSAL FACILITY,MELISSA,TX,75454,3820 SAM RAYBURN HIGHWAY,COLLIN COUNTY,33.29857,-96.53586,Waste,NaN,2010
1,1000112,23rd and 3rd,BROOKLYN,NY,11232,730 3rd Avenue,Kings,40.66300,-74.00000,Power Plants,38.25,2010
2,1006394,29-6 #2 Central Delivery Point,Blanco,NM,87412,NaN,Rio Arriba,36.74520,-107.44550,Petroleum and Natural Gas Systems,11.75,2010
3,1002885,30-5 Central Delivery Point Compressor Station,Aztec,NM,87410,NaN,Rio Arriba,36.81180,-107.40360,Petroleum and Natural Gas Systems,18.25,2010
4,1002707,31-6 Central Delivery Point,BLOOMFIELD,NM,87413,NaN,Rio Arriba,36.83630,-107.41990,Petroleum and Natural Gas Systems,30.00,2010

In [6]:
# This is waste data, no emissions
#93 rows × 8 columns
df4.head()

,name,lat,lng,category,Estimated amount of included waste,Waste concentration,Informal Sector,Status
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active

In [7]:
# This is waste data, no emissions
#569 rows × 9 columns
df5.head()

,name,lat,lng,category,Status,Area,Amount of waste disposed,Annual capacity,Population served
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572

In [8]:
#47 rows x 15 columns
df6.head()

,country,City,state,waste,population,Year,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
0,India,Baidyabati,NaN,63.0,121110,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,India,Bangalore,NaN,4500.0,9590000,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nepal,Bhaktapur,NaN,30.0,"83,893\n\n\n",2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mongolia,Bulgan,NaN,7.3,12486,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sri Lanka,NaN,NaN,1585.0,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
#3448 rows × 33 columns
df7.head()

,GHGRP ID,Landfill ID,Landfill Name,State,Physical Address,City,County,Zip Code,Latitude,Longitude,...,Project Start Date,Project Shutdown Date,Project Type Category,LFG Energy Project Type,RNG Delivery Method,Actual MW Generation,Rated MW Capacity,LFG Flow to Project (mmscfd),Current Year Emission Reductions (MMTCO2e/yr) - Direct,Current Year Emission Reductions (MMTCO2e/yr) - Avoided
0,NaN,10960,Kodiak Island Borough Landfill,AK,1203 Monashka Bay Road,Kodiak,Kodiak Island,99615,57.80874,-152.40761,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
1,1006806.0,10961,South Cushman Landfill,AK,455 Sanduri Street,Fairbanks,Fairbanks North Star,99701,64.80476,-147.70085,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
2,1011448.0,10980,Palmer Central Landfill,AK,1201 N. 49th State Street\nJust off the Palmer...,Palmer,Matanuska-Susitna,99645,61.59000,-149.21000,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11000,Unalaska Landfill,AK,1181 Summer Bay Road,Unalaska,Aleutians West,99685,53.88463,-166.50657,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
4,1004380.0,11020,Merrill Field Landfill,AK,800 Merrill Field Drive,Anchorage,Anchorage,99501,61.21266,-149.84012,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:

# The plan is to join all of the emissions data (df1 and df3)
# Then join all of the waste data (df2, df4, df5, df6)

In [10]:
# Lets start by working on the emissions data

In [62]:
### doing some basic renaming, reshaping, and subsetting for merging purposing

df1.rename(columns={'iso3_country':'country','emissions_quantity':'emissions' }, inplace=True)
df1['Year'] = '2021'
df1['Data Source'] = 'Climate Trace'

df1_clean = df1[df1["gas"] == 'ch4']
df1_clean = df1_clean[['asset_id', 'country', 'emissions', 'asset_name', 'asset_type', 'Year', 'Data Source']]

#before dropping NAs there were 4745 rows
df1_clean.dropna(subset = ['emissions'], inplace=True)

#after dropping NAs there are 4745 rows

df1_clean['emissions'] = df1_clean['emissions'].round(2)
df1_clean.head()

,asset_id,country,emissions,asset_name,asset_type,Year,Data Source
1,1835960681,KOR,228071.91,Sudokwon,Sanitary Landfills,2021,Climate Trace
6,1835960682,TUR,131856.52,Odayeri,Sanitary Landfills,2021,Climate Trace
11,1835960683,CHN,131104.99,Laogang Landfill,Sanitary Landfill,2021,Climate Trace
16,1835960821,USA,9868.23,King George Landfill Inc.,Sanitary Landfills,2021,Climate Trace
19,1835960684,CHN,104839.59,Jiangcungou Landfill,Sanitary Landfill,2021,Climate Trace

In [63]:
### doing some basic renaming, reshaping, and subsetting for the purpose of merging df1 and df3 together


df3.rename(columns={'Facility Id':'asset_id', 'Facility Name': 'asset_name', 'Latitude': 'latitude',
                   'Longitude': 'longitude', 'State': 'state'}, inplace=True)
df3['Data Source'] = 'LMOP'

df3_clean = df3[df3["Industry Type (sectors)"] == 'Waste']
df3_clean['country'] = 'United States'
df3_clean['City'] = df3_clean['City'].str.title()

#before dropping NAs there were 15177 rows
df3_clean.dropna(subset = ['emissions'], inplace=True)
df3_clean
#after dropping NAs there are 15142 rows

df3_clean['emissions'] = df3_clean['emissions'].round(2)

df3_clean = df3_clean[['asset_id', 'asset_name', 'City', 'state', 'country', 'latitude', 'longitude', 'emissions', 'Year', 'Data Source']]


df3_clean.head()

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,asset_id,asset_name,City,state,country,latitude,longitude,emissions,Year,Data Source
5,1003742,31st Street Landfill,Westchester,IL,United States,41.834910,-87.916330,12869.00,2010,LMOP
19,1004680,58TH ST LF (MAIN COUNTY LF),Miami,FL,United States,25.826210,-80.340819,112945.50,2010,LMOP
37,1006529,ACADIA PARISH POLICE JURY - ACADIA PARISH SANI...,Egan,LA,United States,30.256038,-92.532637,46724.25,2010,LMOP
51,1001991,ADRIAN LANDFILL,Adrian,MI,United States,41.890683,-83.992445,75955.00,2010,LMOP
52,1001633,ADS-CEDAR HILL LANDFILL,Ragland,AL,United States,33.676247,-86.254440,97335.00,2010,LMOP

In [60]:
df7.head()

,GHGRP ID,Landfill ID,Landfill Name,State,Physical Address,City,County,Zip Code,Latitude,Longitude,...,Project Start Date,Project Shutdown Date,Project Type Category,LFG Energy Project Type,RNG Delivery Method,Actual MW Generation,Rated MW Capacity,LFG Flow to Project (mmscfd),Current Year Emission Reductions (MMTCO2e/yr) - Direct,Current Year Emission Reductions (MMTCO2e/yr) - Avoided
0,NaN,10960,Kodiak Island Borough Landfill,AK,1203 Monashka Bay Road,Kodiak,Kodiak Island,99615,57.80874,-152.40761,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
1,1006806.0,10961,South Cushman Landfill,AK,455 Sanduri Street,Fairbanks,Fairbanks North Star,99701,64.80476,-147.70085,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
2,1011448.0,10980,Palmer Central Landfill,AK,1201 N. 49th State Street\nJust off the Palmer...,Palmer,Matanuska-Susitna,99645,61.59000,-149.21000,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11000,Unalaska Landfill,AK,1181 Summer Bay Road,Unalaska,Aleutians West,99685,53.88463,-166.50657,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
4,1004380.0,11020,Merrill Field Landfill,AK,800 Merrill Field Drive,Anchorage,Anchorage,99501,61.21266,-149.84012,...,NaT,NaT,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
### doing some basic renaming, reshaping, and subsetting for the purpose of merging df1 and df3 together


df7.rename(columns={'Landfill ID':'asset_id', 'Landfill Name': 'asset_name', 'Latitude': 'latitude',
                   'Longitude': 'longitude', 'State': 'state', 'Current Landfill Status': 'Status'}, inplace=True)
df7['Data Source'] = 'LMOP_full'


df7_clean = df7[['asset_id', 'asset_name', 'City', 'state','latitude', 'longitude', 'Year Landfill Opened', 
                       'Landfill Closure Year', 'Status', 'Waste in Place (tons)', 'Waste in Place Year','Data Source']]


df7_clean.head()

,asset_id,asset_name,City,state,latitude,longitude,Year Landfill Opened,Landfill Closure Year,Status,Waste in Place (tons),Waste in Place Year,Data Source
0,10960,Kodiak Island Borough Landfill,Kodiak,AK,57.80874,-152.40761,NaN,2014.0,Closed,228688.0,2007.0,LMOP_full
1,10961,South Cushman Landfill,Fairbanks,AK,64.80476,-147.70085,1963.0,2088.0,Open,4499106.0,2020.0,LMOP_full
2,10980,Palmer Central Landfill,Palmer,AK,61.59000,-149.21000,1980.0,2150.0,Open,2020681.0,2020.0,LMOP_full
3,11000,Unalaska Landfill,Unalaska,AK,53.88463,-166.50657,1970.0,2013.0,Closed,NaN,NaN,LMOP_full
4,11020,Merrill Field Landfill,Anchorage,AK,61.21266,-149.84012,1960.0,1987.0,Closed,3295353.0,1987.0,LMOP_full

In [66]:
# Merging df1 and df3 together to get a dataset on emissions

df_emissions = pd.concat([df1_clean, df3_clean, df7_clean], ignore_index=False, axis=0)
df_emissions.to_excel("emissions.xlsx") 
df_emissions

#final dataset has 23335 rows × 16 columns
# so 19888 asset level data points for emissions 
# and 15142 city level data points for emissions 
# 3448 rows have the variable 'waste in place'

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

,City,Data Source,Landfill Closure Year,Status,Waste in Place (tons),Waste in Place Year,Year,Year Landfill Opened,asset_id,asset_name,asset_type,country,emissions,latitude,longitude,state
1,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960681,Sudokwon,Sanitary Landfills,KOR,228071.91,NaN,NaN,NaN
6,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960682,Odayeri,Sanitary Landfills,TUR,131856.52,NaN,NaN,NaN
11,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960683,Laogang Landfill,Sanitary Landfill,CHN,131104.99,NaN,NaN,NaN
16,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960821,King George Landfill Inc.,Sanitary Landfills,USA,9868.23,NaN,NaN,NaN
19,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960684,Jiangcungou Landfill,Sanitary Landfill,CHN,104839.59,NaN,NaN,NaN
26,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960822,Tessman Road Landfill,Sanitary Landfills,USA,9855.91,NaN,NaN,NaN
29,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960685,Tehran Landfill,Sanitary Landfills,IRN,103696.80,NaN,NaN,NaN
36,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960823,Greengairs,Sanitary Landfills,GBR,9852.29,NaN,NaN,NaN
39,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960686,Xingfeng,Sanitary Landfills,CHN,99311.31,NaN,NaN,NaN
46,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960824,Moretown Landfill Inc.,Sanitary Landfills,USA,9851.07,NaN,NaN,NaN
49,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960687,West New Territories Landfill,Sanitary Landfills,HKG,93469.47,NaN,NaN,NaN
56,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960825,Cedar Hills Regional Lf,Sanitary Landfills,USA,9794.48,NaN,NaN,NaN
59,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960688,Loma Los Colorados,Sanitary Landfills,CHL,82250.62,NaN,NaN,NaN
66,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960826,Monarch Hill Landfill,Sanitary Landfills,USA,9777.45,NaN,NaN,NaN
69,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960689,South East New Territories Landfill,Sanitary Landfills,HKG,70102.10,NaN,NaN,NaN
76,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960827,Roosevelt Regional Msw Landfill,Sanitary Landfills,USA,9773.00,NaN,NaN,NaN
79,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960690,Komurcuoda,Sanitary Landfills,TUR,59934.78,NaN,NaN,NaN
86,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960828,Environmental Complex Norte Iii,Sanitary Landfills,ARG,9740.92,NaN,NaN,NaN
89,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960691,Fyli Landfill,Sanitary Landfills,GRC,55829.66,NaN,NaN,NaN
96,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960829,Fort Bend Regional Landfill,Sanitary Landfills,USA,9668.21,NaN,NaN,NaN
99,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960692,Casablanca Disposal Site,Sanitary Landfills,MAR,54070.48,NaN,NaN,NaN
106,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960830,River Birch Landfill,Sanitary Landfills,USA,9655.30,NaN,NaN,NaN
109,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960693,Rainham,Sanitary Landfills,GBR,49261.46,NaN,NaN,NaN
116,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960831,Bridgeway Acres Lf,Sanitary Landfills,USA,9496.77,NaN,NaN,NaN
119,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960694,Ghabawi,Sanitary Landfills,JOR,42325.23,NaN,NaN,NaN
126,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960832,Mehmood Booti,Dumpsites,PAK,9478.94,NaN,NaN,NaN
129,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960695,Asmoc,Sanitary Landfills,BRA,40631.36,NaN,NaN,NaN
136,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960833,"Paşaköy İç Yolu, Ayvacık, Canakkale, Marmara R...",Dumpsites,TUR,9444.95,NaN,NaN,NaN
139,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960696,North East Territories Landfill,Sanitary Landfills,HKG,39432.43,NaN,NaN,NaN
147,NaN,Climate Trace,NaN,NaN,NaN,NaN,2021,NaN,1835960834,Mccarty Road Lf,Sanitary Landfills,USA,9426.60,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3418,Weyerhaeuser,LMOP_full,2045.0,Open,4503775.0,2020.0,NaN,1995.0,2407,Timberline Trail Recycling & Disposal Facility,NaN,NaN,NaN,45.454170,-91.358380,WI
3419,Weyerhaeuser,LMOP_full,2045.0,Open,4503775.0,2020.0,NaN,1995.0,2407,Timberline Trail Recycling & Disposal Facility,NaN,NaN,NaN,45.454170,-91.358380,WI
3420,Colliers,LMOP_full,2056.0,Open,3199244.0,2015.0,NaN,1970.0,10160,Brooke County LF (Subtitle D),NaN,NaN,NaN,40.381230,-80.577510,WV
3421,Martinsburg,LMOP_full,1991.0,Closed,NaN,NaN,NaN,1975.0,11200,Berkeley County Landfill,NaN,NaN,NaN,NaN,NaN,WV
3422,Capels,LMOP_full,2110.0,Open,NaN,NaN,NaN,2007.0,11961,Copper Ridge LF,NaN,NaN,NaN,37.480000,-81.600000,WV
3423,Webster Springs,LMOP_full,2002.0,Closed,NaN,NaN,NaN,NaN,21067,Webster County Landfill,NaN,NaN,NaN,38.443134,-80.460525,WV
3424,Beckley,LMOP_full,2070.0,Open,4015471.0,2020.0,NaN,1974.0,2150,Raleigh County SWA Landfill,NaN,NaN,NaN,37.816700,-81.163100,WV
3425,Hurricane,LMOP_full,2044.0,Open,4064511.0,2020.0,NaN,1980.0,2205,Disposal Service Inc. Landfill,NaN,NaN,NaN,38.405000,-82.019000,WV
3426,Bridgeport,LMOP_full,2100.0,Open,8356838.0,2020.0,NaN,1975.0,2206,Meadowfill Landfill,NaN,NaN,NaN,39.338610,-80.256940,WV
3427,Charleston,LMOP_full,2027.0,Open,5344029.0,2020.0,NaN,1971.0,2207,City of Charleston Landfill,NaN,NaN,NaN,38.312790,-81.618540,WV
3428,Charleston,LMOP_full,2027.0,Open,5344029.0,2020.0,NaN,1971.0,2207,City of Charleston Landfill,NaN,NaN,NaN,38.312790,-81.618540,WV
3429,Hedgesville,LMOP_full,2065.0,Open,3175552.0,2020.0,NaN,1991.0,2208,LCS Services Landfill,NaN,NaN,NaN,39.573020,-77.987880,WV
3430,Clarksburg,LMOP_full,2022.0,Open,2995927.0,2020.0,NaN,1975.0,2209,S & S Grading Inc. Landfill,NaN,NaN,NaN,39.220570,-80.408320,WV
3431,Peterstown,LMOP_full,2046.0,Open,NaN,NaN,NaN,2004.0,2210,Ham Sanitary Landfill Inc.,NaN,NaN,NaN,37.436320,-80.769180,WV
3432,Parkersburg,LMOP_full,2064.0,Open,7927296.0,2020.0,NaN,1975.0,2212,Northwestern Landfill,NaN,NaN,NaN,39.249230,-81.492490,WV
3433,Davis,LMOP_full,NaN,Open,2076056.0,2006.0,NaN,1989.0,2214,Tucker County Landfill,NaN,NaN,NaN,39.142000,-79.470000,WV
3434,Princeton,LMOP_full,2064.0,Open,2072876.0,2020.0,NaN,1976.0,2215,Mercer County Landfill,NaN,NaN,NaN,37.331990,-81.124970,WV
3435,Hurricane,LMOP_full,2067.0,Open,4487821.0,2020.0,NaN,1990.0,2216,Sycamore Landfill,NaN,NaN,NaN,38.399500,-82.025000,WV
3436,Dunmore,LMOP_full,NaN,Open,NaN,NaN,NaN,1986.0,2218,Pocahontas County Landfill,NaN,NaN,NaN,38.279000,-79.936500,WV
3437,Elkins,LMOP_full,2056.0,Open,NaN,NaN,NaN,1975.0,2219,Elkins Landfill,NaN,NaN,NaN,38.929000,-79.986550,WV
3438,Lewisburg,LMOP_full,2041.0,Open,780000.0,2006.0,NaN,1976.0,2220,Greenbrier County Landfill,NaN,NaN,NaN,37.827600,-80.379300,WV
3439,Calvin,LMOP_full,2036.0,Open,NaN,NaN,NaN,NaN,2222,Nicholas County Solid Waste Authority LF,NaN,NaN,NaN,38.338500,-80.710000,WV
3440,Bluefield,LMOP_full,NaN,Unknown,NaN,NaN,NaN,NaN,2223,Philip Gwinn Landfill,NaN,NaN,NaN,NaN,NaN,WV
3441,Wheeling,LMOP_full,2053.0,Open,7357873.0,2020.0,NaN,1980.0,2224,Short Creek Sanitary Landfill,NaN,NaN,NaN,40.148310,-80.641120,WV
3442,New Martinsville,LMOP_full,2045.0,Open,1000000.0,2002.0,NaN,1988.0,2225,Wetzel County Landfill,NaN,NaN,NaN,39.605020,-80.856390,WV
3443,Evansville,LMOP_full,2072.0,Open,4397965.0,2020.0,NaN,1966.0,11100,Casper Balefill,NaN,NaN,NaN,42.873192,-106.283097,WY
3444,Sheridan,LMOP_full,NaN,Open,400637.0,2008.0,NaN,1984.0,11140,Sheridan Existing Landfill,NaN,NaN,NaN,44.804335,-106.923406,WY
3445,Gillette,LMOP_full,2052.0,Open,1086553.0,2020.0,NaN,1987.0,20722,Campbell County Landfill No.2,NaN,NaN,NaN,44.392560,-105.490380,WY
3446,Burns,LMOP_full,2146.0,Open,211813.0,2019.0,NaN,1981.0,21136,Eastern Laramie County SWDD,NaN,NaN,NaN,41.230852,-104.336488,WY
3447,Cheyenne,LMOP_full,2045.0,Open,4208224.0,2020.0,NaN,1966.0,2196,Cheyenne Landfill,NaN,NaN,NaN,41.135000,-105.005000,WY

In [6]:
# Now lets move onto to the waste data

In [98]:
### doing some basic renaming, reshaping, and subsetting for the purpose of merging df2, df4, and df5


# Want to make sure each dataset has a year so we can create a time series
df2['Year'] = '2016'
df2['Data Source'] = 'World Bank'

df2.rename(columns={'iso3c':'country', 'country_name':'country_full', 'city_name': 'City', 
                    'total_msw_total_msw_generated_tons_year': 'waste',
                   'population_population_number_of_people':'population',
                   'primary_collection_mode_form_of_primary_collection_na':'collection_method',
                   }, inplace=True)
df2

,country,region_id,country_full,income_id,City,population,collection_method,waste,composition_food_organic_waste_percent,composition_glass_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,Year,Data Source
0,AFG,SAS,Afghanistan,LIC,Jalalabad,326585,Door-to-door collection,58914.45,1.0455,1.1175,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
1,AFG,SAS,Afghanistan,LIC,Kandahar,429000,Centralized drop-off point,120971,11.6000,2.3110,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,635250,Centralized drop-off point,52368.4,50.5000,1.3200,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
3,AFG,SAS,Afghanistan,LIC,Kabul,3700000,Centralized drop-off point,1989250,13.5000,1.0000,...,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00,2016,World Bank
4,AFG,SAS,Afghanistan,LIC,Hirat√Ç¬†,337000,Door-to-door collection,91644.7,52.9400,1.4700,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
5,AGO,SSF,Angola,LMC,Luanda,4508000,NaN,1316336,21.0000,6.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
6,ALB,ECS,Albania,UMC,Korca,51152,Curbside collection,21000,37.0000,2.0000,...,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
7,ALB,ECS,Albania,UMC,Vlora,79513,Curbside collection,37955,40.4200,4.4700,...,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN,2016,World Bank
8,ARE,MEA,United Arab Emirates,HIC,Abu Dhabi,1145000,Curbside collection,1033543,39.0000,4.0000,...,NaN,NaN,9.00,62.00,NaN,20.00,NaN,NaN,2016,World Bank
9,ARE,MEA,United Arab Emirates,HIC,Dubai,2415000,Curbside,2689808,35.4200,3.4200,...,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN,2016,World Bank
10,ARG,LCN,Argentina,HIC,C√É¬≥rdoba,1329604,Multiple,488735,35.0000,3.0000,...,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN,2016,World Bank
11,ARG,LCN,Argentina,HIC,Rosario,1193605,Multiple,438730,58.3800,4.9300,...,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN,2016,World Bank
12,ARG,LCN,Argentina,HIC,Ciudada Aut√É¬≥noma De Buenos Aires (Caba).,2981781,Multiple,2532005,38.0000,6.0000,...,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88,2016,World Bank
13,ARM,ECS,Armenia,UMC,Vanadzor,86199,Curbside collection,23596.97,28.0000,6.0000,...,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00,2016,World Bank
14,ARM,ECS,Armenia,UMC,Spitak,12881,Curbside collection,2866,29.5000,6.7500,...,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84,2016,World Bank
15,AUS,EAS,Australia,HIC,Canberra,353626,Curbside collection,350000,47.0000,7.0000,...,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00,2016,World Bank
16,AUT,ECS,Austria,HIC,Vienna,1741246,Door-to-door collection: waste collector knock...,1036879,31.4000,8.3000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
17,AZE,ECS,Azerbaijan,UMC,Baku,2374000,Curbside collection,1965922,41.7000,6.4000,...,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22,2016,World Bank
18,BDI,SSF,Burundi,LIC,Muyinga,632409,NaN,5657.5,NaN,NaN,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
19,BDI,SSF,Burundi,LIC,Kayanza,585412,NaN,4015,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
20,BDI,SSF,Burundi,LIC,Ngozi,39884,NaN,6752.5,NaN,NaN,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
21,BDI,SSF,Burundi,LIC,Bujumbura,412000,Door-to-door collection,210532,NaN,NaN,...,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank
22,BEL,ECS,Belgium,HIC,Brussels,1154635,Other,469559,NaN,22.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
23,BEL,ECS,Belgium,HIC,Liege,1020579,Other,525300,NaN,NaN,...,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN,2016,World Bank
24,BEN,SSF,Benin,LIC,Porto Novo,600000,NaN,109500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
25,BEN,SSF,Benin,LIC,Cotonou,642000,Door-to-door collection,258420,58.2400,0.8600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
26,BFA,SSF,Burkina Faso,LIC,Bobo Dioulasso,365000,NaN,90000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
27,BFA,SSF,Burkina Faso,LIC,Ouagadougou,1328000,Door-to-door collection: waste collector knock...,315068,39.0000,3.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
28,BGD,SAS,Bangladesh,LMC,Patuakhali,65000,Centralized drop-off point,5220,84.3700,0.6300,...,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00,2016,World Bank
29,BGD,SAS,Bangladesh,LMC,Chittagong,2581643,Door-to-door collection,320380,79.0300,0.2200,...,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00,2016,World Bank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,TUR,ECS,Turkey,UMC,Sakarya Mm,925662,NaN,358139,40.6000,4.4000,...,NaN,NaN,NaN,NaN,NaN,2.49,NaN,97.51,2016,World Bank
300,TUR,ECS,Turkey,UMC,Bursa Mm (Metropolitan Municipality),2764826,NaN,1069711,39.4000,4.9000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
301,TZA,SSF,Tanzania,LIC,Dar Es Salaam,4364541,Multiple,1496500,45.0000,2.9000,...,NaN,NaN,NaN,NaN,18.00,13.00,28.00,41.00,2016,World Bank
302,TZA,SSF,Tanzania,LIC,Moshi,183520,NaN,62050,65.0000,3.0000,...,49.00,NaN,NaN,NaN,NaN,NaN,NaN,31.00,2016,World Bank
303,TZA,SSF,Tanzania,LIC,Mountain Kilimanjaro,210000,NaN,50000,55.0000,1.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
304,UGA,SSF,Uganda,LIC,Kampala,1936000,NaN,840000,73.8000,0.9000,...,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
305,UKR,ECS,Ukraine,LMC,Pavlograd,109885,Other,84600,20.6000,10.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
306,UKR,ECS,Ukraine,LMC,Kiev,2942000,NaN,1100000,35.0000,10.0000,...,NaN,23.00,70.60,NaN,NaN,6.40,NaN,NaN,2016,World Bank
307,URY,LCN,Uruguay,HIC,Montevideo,1319108,Centralized drop-off point,481800,40.9500,5.7300,...,71.00,NaN,NaN,NaN,NaN,29.00,NaN,NaN,2016,World Bank
308,USA,NAC,United States,HIC,Seattle,631350,Curbside collection,720904,53.8000,2.3000,...,41.95,NaN,NaN,NaN,NaN,58.04,NaN,NaN,2016,World Bank
309,USA,NAC,United States,HIC,Washington Dc,693972,Curbside collection,479930.77,83.8600,NaN,...,56.00,NaN,NaN,NaN,NaN,11.00,NaN,NaN,2016,World Bank
310,USA,NAC,United States,HIC,Ann Arbor,307000,NaN,200767.82,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,31.00,NaN,NaN,2016,World Bank
311,UZB,ECS,Uzbekistan,LMC,Tashkent,2251000,Centralized drop-off point,500000,38.4000,3.7000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
312,VEN,LCN,"Venezuela, RB",UMC,Caracas,3220540,Centralized drop-off point,1787940,50.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,0.90,99.10,NaN,2016,World Bank
313,VNM,EAS,Vietnam,LMC,Hanoi,3629000,Door-to-door collection,2390750,59.1000,2.4000,...,NaN,5.40,10.91,NaN,NaN,8.20,63.64,10.00,2016,World Bank
314,VNM,EAS,Vietnam,LMC,Ho Chi Minh City,7981900,Door-to-door collection,2518500,69.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,85.00,NaN,2016,World Bank
315,VUT,EAS,Vanuatu,LMC,Port Vila,44039,Door-to-door collection,27000,62.8000,7.8000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
316,XKX,ECS,Kosovo,LMC,Gjilan,90015,NaN,27000,NaN,NaN,...,NaN,NaN,100.00,NaN,NaN,0.00,NaN,NaN,2016,World Bank
317,XKX,ECS,Kosovo,LMC,Pristina,210000,Other,130928,40.8700,4.4500,...,80.00,NaN,NaN,10.00,NaN,10.00,NaN,NaN,2016,World Bank
318,YEM,MEA,"Yemen, Rep.",LIC,Sana√É¬°,2330689,Door-to-door collection,510420.89,65.0000,1.0000,...,53.00,NaN,NaN,NaN,NaN,12.00,NaN,30.00,2016,World Bank
319,ZAF,SSF,South Africa,UMC,Johannesburg√Ç¬†,4434827,NaN,1867000,NaN,NaN,...,NaN,NaN,95.00,NaN,NaN,NaN,NaN,NaN,2016,World Bank
320,ZAF,SSF,South Africa,UMC,Cape Town,3430000,NaN,1251950,47.0000,4.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
321,ZAF,SSF,South Africa,UMC,Durban,2739000,NaN,1421541,42.5000,7.1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
322,ZMB,SSF,Zambia,LMC,Ndola√Ç¬†,453000,NaN,85979.4,40.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
323,ZMB,SSF,Zambia,LMC,Lusaka,1719000,NaN,530000,40.0000,2.0000,...,26.00,NaN,NaN,NaN,NaN,6.00,NaN,68.00,2016,World Bank
324,ZWE,SSF,Zimbabwe,LIC,Norton,58421,NaN,14021.04,62.3000,2.7000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
325,ZWE,SSF,Zimbabwe,LIC,Chinhoyi,98000,NaN,25480,62.8000,3.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
326,ZWE,SSF,Zimbabwe,LIC,Harare√Ç¬†,1379000,Door-to-door collection,352334.5,22.6100,6.4500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
327,ZWE,SSF,Zimbabwe,LIC,Gweru,157865,NaN,37887.6,62.4000,3.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank
328,ZWE,SSF,Zimbabwe,LIC,Kariba,26512,NaN,7423.36,52.0000,2.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank

In [99]:
# Create a new column 'availble city data' based on if the 'city' column is available or if it is missing. 
# If the value is FALSE, then that means the cities were generated through the java script code provided by Andre
df2['Available City Data'] = df2['City'].notna()
df2_clean = df2

df2_clean

,country,region_id,country_full,income_id,City,population,collection_method,waste,composition_food_organic_waste_percent,composition_glass_percent,...,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,Year,Data Source,Available City Data
0,AFG,SAS,Afghanistan,LIC,Jalalabad,326585,Door-to-door collection,58914.45,1.0455,1.1175,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
1,AFG,SAS,Afghanistan,LIC,Kandahar,429000,Centralized drop-off point,120971,11.6000,2.3110,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,635250,Centralized drop-off point,52368.4,50.5000,1.3200,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
3,AFG,SAS,Afghanistan,LIC,Kabul,3700000,Centralized drop-off point,1989250,13.5000,1.0000,...,NaN,NaN,75.00,NaN,NaN,NaN,25.00,2016,World Bank,True
4,AFG,SAS,Afghanistan,LIC,Hirat√Ç¬†,337000,Door-to-door collection,91644.7,52.9400,1.4700,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
5,AGO,SSF,Angola,LMC,Luanda,4508000,NaN,1316336,21.0000,6.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
6,ALB,ECS,Albania,UMC,Korca,51152,Curbside collection,21000,37.0000,2.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
7,ALB,ECS,Albania,UMC,Vlora,79513,Curbside collection,37955,40.4200,4.4700,...,NaN,NaN,90.00,NaN,10.00,NaN,NaN,2016,World Bank,True
8,ARE,MEA,United Arab Emirates,HIC,Abu Dhabi,1145000,Curbside collection,1033543,39.0000,4.0000,...,NaN,9.00,62.00,NaN,20.00,NaN,NaN,2016,World Bank,True
9,ARE,MEA,United Arab Emirates,HIC,Dubai,2415000,Curbside,2689808,35.4200,3.4200,...,NaN,NaN,NaN,NaN,25.00,75.00,NaN,2016,World Bank,True
10,ARG,LCN,Argentina,HIC,C√É¬≥rdoba,1329604,Multiple,488735,35.0000,3.0000,...,NaN,NaN,30.00,NaN,0.68,NaN,NaN,2016,World Bank,True
11,ARG,LCN,Argentina,HIC,Rosario,1193605,Multiple,438730,58.3800,4.9300,...,NaN,NaN,NaN,NaN,NaN,89.19,NaN,2016,World Bank,True
12,ARG,LCN,Argentina,HIC,Ciudada Aut√É¬≥noma De Buenos Aires (Caba).,2981781,Multiple,2532005,38.0000,6.0000,...,NaN,NaN,NaN,14.42,7.20,61.50,16.88,2016,World Bank,True
13,ARM,ECS,Armenia,UMC,Vanadzor,86199,Curbside collection,23596.97,28.0000,6.0000,...,NaN,NaN,90.00,NaN,NaN,NaN,10.00,2016,World Bank,True
14,ARM,ECS,Armenia,UMC,Spitak,12881,Curbside collection,2866,29.5000,6.7500,...,NaN,NaN,93.16,NaN,NaN,NaN,6.84,2016,World Bank,True
15,AUS,EAS,Australia,HIC,Canberra,353626,Curbside collection,350000,47.0000,7.0000,...,NaN,NaN,NaN,NaN,70.00,NaN,2.00,2016,World Bank,True
16,AUT,ECS,Austria,HIC,Vienna,1741246,Door-to-door collection: waste collector knock...,1036879,31.4000,8.3000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
17,AZE,ECS,Azerbaijan,UMC,Baku,2374000,Curbside collection,1965922,41.7000,6.4000,...,24.21,NaN,NaN,NaN,NaN,36.36,49.22,2016,World Bank,True
18,BDI,SSF,Burundi,LIC,Muyinga,632409,NaN,5657.5,NaN,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
19,BDI,SSF,Burundi,LIC,Kayanza,585412,NaN,4015,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
20,BDI,SSF,Burundi,LIC,Ngozi,39884,NaN,6752.5,NaN,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
21,BDI,SSF,Burundi,LIC,Bujumbura,412000,Door-to-door collection,210532,NaN,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,2016,World Bank,True
22,BEL,ECS,Belgium,HIC,Brussels,1154635,Other,469559,NaN,22.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
23,BEL,ECS,Belgium,HIC,Liege,1020579,Other,525300,NaN,NaN,...,26.00,NaN,NaN,NaN,53.00,4.00,NaN,2016,World Bank,True
24,BEN,SSF,Benin,LIC,Porto Novo,600000,NaN,109500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
25,BEN,SSF,Benin,LIC,Cotonou,642000,Door-to-door collection,258420,58.2400,0.8600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
26,BFA,SSF,Burkina Faso,LIC,Bobo Dioulasso,365000,NaN,90000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
27,BFA,SSF,Burkina Faso,LIC,Ouagadougou,1328000,Door-to-door collection: waste collector knock...,315068,39.0000,3.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
28,BGD,SAS,Bangladesh,LMC,Patuakhali,65000,Centralized drop-off point,5220,84.3700,0.6300,...,NaN,NaN,55.45,NaN,4.55,NaN,40.00,2016,World Bank,True
29,BGD,SAS,Bangladesh,LMC,Chittagong,2581643,Door-to-door collection,320380,79.0300,0.2200,...,NaN,NaN,29.17,NaN,12.41,NaN,58.00,2016,World Bank,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,TUR,ECS,Turkey,UMC,Sakarya Mm,925662,NaN,358139,40.6000,4.4000,...,NaN,NaN,NaN,NaN,2.49,NaN,97.51,2016,World Bank,True
300,TUR,ECS,Turkey,UMC,Bursa Mm (Metropolitan Municipality),2764826,NaN,1069711,39.4000,4.9000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
301,TZA,SSF,Tanzania,LIC,Dar Es Salaam,4364541,Multiple,1496500,45.0000,2.9000,...,NaN,NaN,NaN,18.00,13.00,28.00,41.00,2016,World Bank,True
302,TZA,SSF,Tanzania,LIC,Moshi,183520,NaN,62050,65.0000,3.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,31.00,2016,World Bank,True
303,TZA,SSF,Tanzania,LIC,Mountain Kilimanjaro,210000,NaN,50000,55.0000,1.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
304,UGA,SSF,Uganda,LIC,Kampala,1936000,NaN,840000,73.8000,0.9000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
305,UKR,ECS,Ukraine,LMC,Pavlograd,109885,Other,84600,20.6000,10.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
306,UKR,ECS,Ukraine,LMC,Kiev,2942000,NaN,1100000,35.0000,10.0000,...,23.00,70.60,NaN,NaN,6.40,NaN,NaN,2016,World Bank,True
307,URY,LCN,Uruguay,HIC,Montevideo,1319108,Centralized drop-off point,481800,40.9500,5.7300,...,NaN,NaN,NaN,NaN,29.00,NaN,NaN,2016,World Bank,True
308,USA,NAC,United States,HIC,Seattle,631350,Curbside collection,720904,53.8000,2.3000,...,NaN,NaN,NaN,NaN,58.04,NaN,NaN,2016,World Bank,True
309,USA,NAC,United States,HIC,Washington Dc,693972,Curbside collection,479930.77,83.8600,NaN,...,NaN,NaN,NaN,NaN,11.00,NaN,NaN,2016,World Bank,True
310,USA,NAC,United States,HIC,Ann Arbor,307000,NaN,200767.82,NaN,NaN,...,NaN,NaN,NaN,NaN,31.00,NaN,NaN,2016,World Bank,True
311,UZB,ECS,Uzbekistan,LMC,Tashkent,2251000,Centralized drop-off point,500000,38.4000,3.7000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
312,VEN,LCN,"Venezuela, RB",UMC,Caracas,3220540,Centralized drop-off point,1787940,50.0000,NaN,...,NaN,NaN,NaN,NaN,0.90,99.10,NaN,2016,World Bank,True
313,VNM,EAS,Vietnam,LMC,Hanoi,3629000,Door-to-door collection,2390750,59.1000,2.4000,...,5.40,10.91,NaN,NaN,8.20,63.64,10.00,2016,World Bank,True
314,VNM,EAS,Vietnam,LMC,Ho Chi Minh City,7981900,Door-to-door collection,2518500,69.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,85.00,NaN,2016,World Bank,True
315,VUT,EAS,Vanuatu,LMC,Port Vila,44039,Door-to-door collection,27000,62.8000,7.8000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
316,XKX,ECS,Kosovo,LMC,Gjilan,90015,NaN,27000,NaN,NaN,...,NaN,100.00,NaN,NaN,0.00,NaN,NaN,2016,World Bank,True
317,XKX,ECS,Kosovo,LMC,Pristina,210000,Other,130928,40.8700,4.4500,...,NaN,NaN,10.00,NaN,10.00,NaN,NaN,2016,World Bank,True
318,YEM,MEA,"Yemen, Rep.",LIC,Sana√É¬°,2330689,Door-to-door collection,510420.89,65.0000,1.0000,...,NaN,NaN,NaN,NaN,12.00,NaN,30.00,2016,World Bank,True
319,ZAF,SSF,South Africa,UMC,Johannesburg√Ç¬†,4434827,NaN,1867000,NaN,NaN,...,NaN,95.00,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
320,ZAF,SSF,South Africa,UMC,Cape Town,3430000,NaN,1251950,47.0000,4.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
321,ZAF,SSF,South Africa,UMC,Durban,2739000,NaN,1421541,42.5000,7.1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
322,ZMB,SSF,Zambia,LMC,Ndola√Ç¬†,453000,NaN,85979.4,40.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
323,ZMB,SSF,Zambia,LMC,Lusaka,1719000,NaN,530000,40.0000,2.0000,...,NaN,NaN,NaN,NaN,6.00,NaN,68.00,2016,World Bank,True
324,ZWE,SSF,Zimbabwe,LIC,Norton,58421,NaN,14021.04,62.3000,2.7000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
325,ZWE,SSF,Zimbabwe,LIC,Chinhoyi,98000,NaN,25480,62.8000,3.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
326,ZWE,SSF,Zimbabwe,LIC,Harare√Ç¬†,1379000,Door-to-door collection,352334.5,22.6100,6.4500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
327,ZWE,SSF,Zimbabwe,LIC,Gweru,157865,NaN,37887.6,62.4000,3.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True
328,ZWE,SSF,Zimbabwe,LIC,Kariba,26512,NaN,7423.36,52.0000,2.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,World Bank,True

In [100]:

#before dropping NAs there were 329 rows × 31 columns
sum(pd.isnull(df2['waste']))
#there were no NAs in waste column

df2_clean.head()

,country,region_id,country_full,income_id,City,population,collection_method,waste,composition_food_organic_waste_percent,composition_glass_percent,...,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,Year,Data Source,Available City Data
0,AFG,SAS,Afghanistan,LIC,Jalalabad,326585,Door-to-door collection,58914.45,1.0455,1.1175,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2016,World Bank,True
1,AFG,SAS,Afghanistan,LIC,Kandahar,429000,Centralized drop-off point,120971,11.6000,2.3110,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2016,World Bank,True
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,635250,Centralized drop-off point,52368.4,50.5000,1.3200,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2016,World Bank,True
3,AFG,SAS,Afghanistan,LIC,Kabul,3700000,Centralized drop-off point,1989250,13.5000,1.0000,...,NaN,NaN,75.0,NaN,NaN,NaN,25.0,2016,World Bank,True
4,AFG,SAS,Afghanistan,LIC,Hirat√Ç¬†,337000,Door-to-door collection,91644.7,52.9400,1.4700,...,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2016,World Bank,True

In [50]:
df4.head()

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites

In [52]:
df4['Year'] = '2015'
df4['Data Source'] = 'Waste Atlas Dumpsites'

df4_clean = df4
df4_clean.rename(columns={'name':'asset_id', 'lat':'latitude', 'lng': 'longitude', 
                    'Waste concentration': 'waste',
                   }, inplace=True)

df4_clean

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,150000 - 214000,1200,Active,2019,Waste Atlas Dumpsites
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,257000 - 360000,5000,Active,2019,Waste Atlas Dumpsites
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,We need your support,Active,2019,Waste Atlas Dumpsites
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,401000 - 573000,1200,Active,2019,Waste Atlas Dumpsites
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,We need your support,Active,2019,Waste Atlas Dumpsites
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,90100 - 128000,1500,Active,2019,Waste Atlas Dumpsites
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,22300 - 31900,2000,Active,2019,Waste Atlas Dumpsites
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,326000 - 466000,420,Active,2019,Waste Atlas Dumpsites
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,326400 - 466300,2000,Active,2019,Waste Atlas Dumpsites
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,112000 - 160000,5000,Active,2019,Waste Atlas Dumpsites
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,215600 - 307800,We need your support,Active,2019,Waste Atlas Dumpsites
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,We need your support,Active,2019,Waste Atlas Dumpsites
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,100000 - 150000,200,Active,2019,Waste Atlas Dumpsites
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,171000 - 242000,0,Active,2019,Waste Atlas Dumpsites
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,We need you support,Active,2019,Waste Atlas Dumpsites
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,We need your support,Active,2019,Waste Atlas Dumpsites
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,200000 - 286000,1000,Active,2019,Waste Atlas Dumpsites
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,We need your support,Active,2019,Waste Atlas Dumpsites
...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,57500 - 82500,50,Active,2019,Waste Atlas Dumpsites
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,418750 - 600000,We need your support,Active,2019,Waste Atlas Dumpsites
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,490000 - 700000,150,Active,2019,Waste Atlas Dumpsites
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,80000 - 127000,0,Active,2019,Waste Atlas Dumpsites
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,190000 - 270000,20,Active,2019,Waste Atlas Dumpsites
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,44000 - 58000,30,Active,2019,Waste Atlas Dumpsites
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,128000 - 183000,300,Active,2019,Waste Atlas Dumpsites
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,48900 - 70800,We need your support,Active,2019,Waste Atlas Dumpsites
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,78260 - 113000,We need your support,Active,2019,Waste Atlas Dumpsites
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,189000 - 272000,100,Active,2019,Waste Atlas Dumpsites
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,412 - 580,200,Active,2019,Waste Atlas Dumpsites
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,166000 - 240000,670,Active,2019,Waste Atlas Dumpsites
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,766000 - 1100000,We need your support,Active,2019,Waste Atlas Dumpsites
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,351800 - 350000,18,Active,2019,Waste Atlas Dumpsites
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,245900 - 250000,We need your support,Active,2019,Waste Atlas Dumpsites
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,222300 - 333000,35,Active,2019,Waste Atlas Dumpsites
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,25200 - 36400,100,Active,2019,Waste Atlas Dumpsites
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,95200 - 142800,40,Active,2019,Waste Atlas Dumpsites
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,212000 - 303000,100,Active,2019,Waste Atlas Dumpsites
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,44100 - 63000,70,Active,2019,Waste Atlas Dumpsites
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,We need your suppor,We need your suppor,3000,Active,2019,Waste Atlas Dumpsites
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,We need your suppor,We need your suppor,We need your support,Active,2019,Waste Atlas Dumpsites
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,We need your suppor,We need your suppor,100,Active,2019,Waste Atlas Dumpsites
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,We need your suppor,We need your suppor,5,Active,2019,Waste Atlas Dumpsites
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,We need your suppor,We need your suppor,35,Active,2019,Waste Atlas Dumpsites
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,We need your suppor,We need your suppor,15-20,Active,2019,Waste Atlas Dumpsites
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,We need your suppor,We need your suppor,70,Active,2019,Waste Atlas Dumpsites
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites

In [53]:
!pip install geopy
import geopy
from geopy.geocoders import Nominatim

# Create a geocoder instance
geolocator = Nominatim(user_agent="my_geocoder")

# Reverse geocode to get the city name
#df4_clean['city'] = df4_clean.apply(lambda row: geolocator.reverse(f"{row['latitude']}, {row['longitude']}").raw['address'].get('city', ''), axis=1)




def town_city_state_country(row):
    coord = f"{row['latitude']}, {row['longitude']}"
    location = geolocator.reverse(coord, exactly_one=True, timeout=None)
    address = location.raw['address']
    city = address.get('city', '')
    state = address.get('state', '')
    country = address.get('country', '')
    town = address.get('town', '')
    row['town'] = town
    row['city'] = city
    row['state'] = state
    row['country'] = country
    
    return row

df4_clean = df4_clean.apply(town_city_state_country, axis=1)
df4_clean

Requirement already satisfied: geopy in /Users/rowansharkey/anaconda3/lib/python3.6/site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /Users/rowansharkey/anaconda3/lib/python3.6/site-packages (from geopy) (1.52)
WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/rowansharkey/anaconda3/bin/python -m pip install --upgrade pip' command.

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,city,state,country
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,,,Estado de México,México
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,,,,România
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,,Duque de Caxias,Rio de Janeiro,Brasil
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites,,Quezon City,,Philippines
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,,,,România
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,150000 - 214000,1200,Active,2019,Waste Atlas Dumpsites,,Managua (Municipio),Managua,Nicaragua
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,257000 - 360000,5000,Active,2019,Waste Atlas Dumpsites,,Kota Bekasi,Jawa Barat,Indonesia
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,,City of New York,New York,United States
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,We need your support,Active,2019,Waste Atlas Dumpsites,,,,India
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,401000 - 573000,1200,Active,2019,Waste Atlas Dumpsites,,Ikeja,Lagos,Nigeria
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,We need your support,Active,2019,Waste Atlas Dumpsites,,,Delhi,India
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,90100 - 128000,1500,Active,2019,Waste Atlas Dumpsites,,Mumbai,Maharashtra,India
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,22300 - 31900,2000,Active,2019,Waste Atlas Dumpsites,,Port-au-Prince,Département de l'Ouest,Ayiti
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,326000 - 466000,420,Active,2019,Waste Atlas Dumpsites,,,Delhi,India
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,326400 - 466300,2000,Active,2019,Waste Atlas Dumpsites,,Ciudad de Guatemala,Departamento de Guatemala,Guatemala
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,112000 - 160000,5000,Active,2019,Waste Atlas Dumpsites,,Cochabamba,Cochabamba,Bolivia
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,,Chennai,Tamil Nadu,India
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,215600 - 307800,We need your support,Active,2019,Waste Atlas Dumpsites,,لاہور,پنجاب,پاکستان
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,We need your support,Active,2019,Waste Atlas Dumpsites,,,Tamil Nadu,India
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,100000 - 150000,200,Active,2019,Waste Atlas Dumpsites,,San Carlos de Bariloche,Río Negro,Argentina
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,171000 - 242000,0,Active,2019,Waste Atlas Dumpsites,,,,Україна
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,,,Україна
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,We need you support,Active,2019,Waste Atlas Dumpsites,,,Московская область,Россия
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,We need your support,Active,2019,Waste Atlas Dumpsites,,Новосибирск,Новосибирская область,Россия
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,,صيدا,محافظة الجنوب,لبنان
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,200000 - 286000,1000,Active,2019,Waste Atlas Dumpsites,,,Чүй облусу,Кыргызстан
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,We need your support,Active,2019,Waste Atlas Dumpsites,,Mar del Plata,Buenos Aires,Argentina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,57500 - 82500,50,Active,2019,Waste Atlas Dumpsites,,غزة,,Palestinian Territory
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,418750 - 600000,We need your support,Active,2019,Waste Atlas Dumpsites,,Pedungan,Bali,Indonesia
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,490000 - 700000,150,Active,2019,Waste Atlas Dumpsites,,Krugersdorp,Gauteng,South Africa
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,80000 - 127000,0,Active,2019,Waste Atlas Dumpsites,,,Karnataka,India
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,190000 - 270000,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,,Централна Србија,Србија
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,44000 - 58000,30,Active,2019,Waste Atlas Dumpsites,,,المفرق,الأردن
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,128000 - 183000,300,Active,2019,Waste Atlas Dumpsites,,Pietermaritzburg,KwaZulu-Natal,South Africa
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,48900 - 70800,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,78260 - 113000,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,189000 - 272000,100,Active,2019,Waste Atlas Dumpsites,,,Eastern Cape,South Africa
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,412 - 580,200,Active,2019,Waste Atlas Dumpsites,Epe,,Lagos,Nigeria
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,166000 - 240000,670,Active,2019,Waste Atlas Dumpsites,,Bamako,,Mali
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,766000 - 1100000,We need your support,Active,2019,Waste Atlas Dumpsites,,Freetown,Western Area Urban,Sierra Leone
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,351800 - 350000,18,Active,2019,Waste Atlas Dumpsites,,,,Palestinian Territory
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,245900 - 250000,We need your support,Active,2019,Waste Atlas Dumpsites,,دير البلح,,Palestinian Territory
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,222300 - 333000,35,Active,2019,Waste Atlas Dumpsites,,Puno,Puno,Perú
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,25200 - 36400,100,Active,2019,Waste Atlas Dumpsites,,,Central Equatoria,South Sudan
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,95200 - 142800,40,Active,2019,Waste Atlas Dumpsites,,Cusco,Cusco,Perú
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,212000 - 303000,100,Active,2019,Waste Atlas Dumpsites,,,Likisá,Timór Lorosa'e / Timor-Leste
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,44100 - 63000,70,Active,2019,Waste Atlas Dumpsites,Yura,,Arequipa,Perú
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,We need your suppor,We need your suppor,3000,Active,2019,Waste Atlas Dumpsites,,Chinandega,Chinandega,Nicaragua
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,Râmnicu Sărat,,,România
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,,Serrekunda,Kanifing,Gambia
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,We need your suppor,We need your suppor,We need your support,Active,2019,Waste Atlas Dumpsites,,,Arta عرتا,Djibouti جيبوتي
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,We need your suppor,We need your suppor,100,Active,2019,Waste Atlas Dumpsites,San Josecito,,Táchira,Venezuela
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,We need your suppor,We need your suppor,5,Active,2019,Waste Atlas Dumpsites,Lluyllucucha,Moyobamba,San Martín,Perú
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,We need your suppor,We need your suppor,35,Active,2019,Waste Atlas Dumpsites,,,Tumbes,Perú
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,We need your suppor,We need your suppor,15-20,Active,2019,Waste Atlas Dumpsites,,Chimbote,Ancash,Perú
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,We need your suppor,We need your suppor,70,Active,2019,Waste Atlas Dumpsites,,Castilla,Piura,Perú
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,,Juliaca,Puno,Perú

In [78]:
# there are still some values missing, but the info in the 'town' column is also a city, so let's replace it.
# Replace blank values in 'city' column with values from 'state' column



df4_clean.city.replace('',df4_clean.town,inplace=True)


df4_clean.rename(columns={'city':'City'
                   }, inplace=True)
df4_clean

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,City,state,country,Available City Data
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,,,Estado de México,México,False
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,,,,România,False
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,,Duque de Caxias,Rio de Janeiro,Brasil,True
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites,,Quezon City,,Philippines,True
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,,,,România,False
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,150000 - 214000,1200,Active,2019,Waste Atlas Dumpsites,,Managua (Municipio),Managua,Nicaragua,True
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,257000 - 360000,5000,Active,2019,Waste Atlas Dumpsites,,Kota Bekasi,Jawa Barat,Indonesia,True
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,,City of New York,New York,United States,True
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,We need your support,Active,2019,Waste Atlas Dumpsites,,,,India,False
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,401000 - 573000,1200,Active,2019,Waste Atlas Dumpsites,,Ikeja,Lagos,Nigeria,True
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,We need your support,Active,2019,Waste Atlas Dumpsites,,,Delhi,India,False
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,90100 - 128000,1500,Active,2019,Waste Atlas Dumpsites,,Mumbai,Maharashtra,India,True
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,22300 - 31900,2000,Active,2019,Waste Atlas Dumpsites,,Port-au-Prince,Département de l'Ouest,Ayiti,True
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,326000 - 466000,420,Active,2019,Waste Atlas Dumpsites,,,Delhi,India,False
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,326400 - 466300,2000,Active,2019,Waste Atlas Dumpsites,,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,112000 - 160000,5000,Active,2019,Waste Atlas Dumpsites,,Cochabamba,Cochabamba,Bolivia,True
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,ខណ្ឌមានជ័យ,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,False
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,,Chennai,Tamil Nadu,India,True
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,215600 - 307800,We need your support,Active,2019,Waste Atlas Dumpsites,,لاہور,پنجاب,پاکستان,True
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,We need your support,Active,2019,Waste Atlas Dumpsites,,,Tamil Nadu,India,False
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,100000 - 150000,200,Active,2019,Waste Atlas Dumpsites,,San Carlos de Bariloche,Río Negro,Argentina,True
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,171000 - 242000,0,Active,2019,Waste Atlas Dumpsites,,,,Україна,False
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,Гаспра,,Україна,False
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,We need you support,Active,2019,Waste Atlas Dumpsites,,,Московская область,Россия,False
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,We need your support,Active,2019,Waste Atlas Dumpsites,,Новосибирск,Новосибирская область,Россия,True
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,,صيدا,محافظة الجنوب,لبنان,True
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,200000 - 286000,1000,Active,2019,Waste Atlas Dumpsites,,,Чүй облусу,Кыргызстан,False
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,We need your support,Active,2019,Waste Atlas Dumpsites,,Mar del Plata,Buenos Aires,Argentina,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,57500 - 82500,50,Active,2019,Waste Atlas Dumpsites,,غزة,,Palestinian Territory,True
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,418750 - 600000,We need your support,Active,2019,Waste Atlas Dumpsites,,Pedungan,Bali,Indonesia,True
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,490000 - 700000,150,Active,2019,Waste Atlas Dumpsites,,Krugersdorp,Gauteng,South Africa,True
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,80000 - 127000,0,Active,2019,Waste Atlas Dumpsites,,,Karnataka,India,False
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,190000 - 270000,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,Градска општина Гроцка,Централна Србија,Србија,False
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,44000 - 58000,30,Active,2019,Waste Atlas Dumpsites,,,المفرق,الأردن,False
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,128000 - 183000,300,Active,2019,Waste Atlas Dumpsites,,Pietermaritzburg,KwaZulu-Natal,South Africa,True
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,48900 - 70800,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,78260 - 113000,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,189000 - 272000,100,Active,2019,Waste Atlas Dumpsites,,,Eastern Cape,South Africa,False
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,412 - 580,200,Active,2019,Waste Atlas Dumpsites,Epe,Epe,Lagos,Nigeria,False
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,166000 - 240000,670,Active,2019,Waste Atlas Dumpsites,,Bamako,,Mali,True
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,766000 - 1100000,We need your support,Active,2019,Waste Atlas Dumpsites,,Freetown,Western Area Urban,Sierra Leone,True
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,351800 - 350000,18,Active,2019,Waste Atlas Dumpsites,,,,Palestinian Territory,False
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,245900 - 250000,We need your support,Active,2019,Waste Atlas Dumpsites,,دير البلح,,Palestinian Territory,True
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,222300 - 333000,35,Active,2019,Waste Atlas Dumpsites,,Puno,Puno,Perú,True
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,25200 - 36400,100,Active,2019,Waste Atlas Dumpsites,,,Central Equatoria,South Sudan,False
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,95200 - 142800,40,Active,2019,Waste Atlas Dumpsites,,Cusco,Cusco,Perú,True
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,212000 - 303000,100,Active,2019,Waste Atlas Dumpsites,,,Likisá,Timór Lorosa'e / Timor-Leste,False
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,44100 - 63000,70,Active,2019,Waste Atlas Dumpsites,Yura,Yura,Arequipa,Perú,False
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,We need your suppor,We need your suppor,3000,Active,2019,Waste Atlas Dumpsites,,Chinandega,Chinandega,Nicaragua,True
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,Râmnicu Sărat,Râmnicu Sărat,,România,False
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,,Serrekunda,Kanifing,Gambia,True
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,We need your suppor,We need your suppor,We need your support,Active,2019,Waste Atlas Dumpsites,,,Arta عرتا,Djibouti جيبوتي,False
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,We need your suppor,We need your suppor,100,Active,2019,Waste Atlas Dumpsites,San Josecito,San Josecito,Táchira,Venezuela,False
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,We need your suppor,We need your suppor,5,Active,2019,Waste Atlas Dumpsites,Lluyllucucha,Moyobamba,San Martín,Perú,True
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,We need your suppor,We need your suppor,35,Active,2019,Waste Atlas Dumpsites,,,Tumbes,Perú,False
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,We need your suppor,We need your suppor,15-20,Active,2019,Waste Atlas Dumpsites,,Chimbote,Ancash,Perú,True
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,We need your suppor,We need your suppor,70,Active,2019,Waste Atlas Dumpsites,,Castilla,Piura,Perú,True
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,,Juliaca,Puno,Perú,True

In [80]:
# Create a new column 'availble city data' based on if the 'city' column is available or if it is missing. 
# If the value is FALSE, then that means the cities were generated through the java script code provided by Andre
df4_clean['Available City Data'] = df4_clean['City'].apply(lambda x: True if x else False)
df4_clean

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,City,state,country,Available City Data
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,,,Estado de México,México,False
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,,,,România,False
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,,Duque de Caxias,Rio de Janeiro,Brasil,True
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites,,Quezon City,,Philippines,True
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,,,,România,False
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,150000 - 214000,1200,Active,2019,Waste Atlas Dumpsites,,Managua (Municipio),Managua,Nicaragua,True
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,257000 - 360000,5000,Active,2019,Waste Atlas Dumpsites,,Kota Bekasi,Jawa Barat,Indonesia,True
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,,City of New York,New York,United States,True
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,We need your support,Active,2019,Waste Atlas Dumpsites,,,,India,False
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,401000 - 573000,1200,Active,2019,Waste Atlas Dumpsites,,Ikeja,Lagos,Nigeria,True
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,We need your support,Active,2019,Waste Atlas Dumpsites,,,Delhi,India,False
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,90100 - 128000,1500,Active,2019,Waste Atlas Dumpsites,,Mumbai,Maharashtra,India,True
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,22300 - 31900,2000,Active,2019,Waste Atlas Dumpsites,,Port-au-Prince,Département de l'Ouest,Ayiti,True
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,326000 - 466000,420,Active,2019,Waste Atlas Dumpsites,,,Delhi,India,False
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,326400 - 466300,2000,Active,2019,Waste Atlas Dumpsites,,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,112000 - 160000,5000,Active,2019,Waste Atlas Dumpsites,,Cochabamba,Cochabamba,Bolivia,True
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,ខណ្ឌមានជ័យ,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,True
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,,Chennai,Tamil Nadu,India,True
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,215600 - 307800,We need your support,Active,2019,Waste Atlas Dumpsites,,لاہور,پنجاب,پاکستان,True
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,We need your support,Active,2019,Waste Atlas Dumpsites,,,Tamil Nadu,India,False
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,100000 - 150000,200,Active,2019,Waste Atlas Dumpsites,,San Carlos de Bariloche,Río Negro,Argentina,True
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,171000 - 242000,0,Active,2019,Waste Atlas Dumpsites,,,,Україна,False
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,Гаспра,,Україна,True
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,We need you support,Active,2019,Waste Atlas Dumpsites,,,Московская область,Россия,False
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,We need your support,Active,2019,Waste Atlas Dumpsites,,Новосибирск,Новосибирская область,Россия,True
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,,صيدا,محافظة الجنوب,لبنان,True
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,200000 - 286000,1000,Active,2019,Waste Atlas Dumpsites,,,Чүй облусу,Кыргызстан,False
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,We need your support,Active,2019,Waste Atlas Dumpsites,,Mar del Plata,Buenos Aires,Argentina,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,57500 - 82500,50,Active,2019,Waste Atlas Dumpsites,,غزة,,Palestinian Territory,True
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,418750 - 600000,We need your support,Active,2019,Waste Atlas Dumpsites,,Pedungan,Bali,Indonesia,True
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,490000 - 700000,150,Active,2019,Waste Atlas Dumpsites,,Krugersdorp,Gauteng,South Africa,True
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,80000 - 127000,0,Active,2019,Waste Atlas Dumpsites,,,Karnataka,India,False
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,190000 - 270000,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,Градска општина Гроцка,Централна Србија,Србија,True
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,44000 - 58000,30,Active,2019,Waste Atlas Dumpsites,,,المفرق,الأردن,False
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,128000 - 183000,300,Active,2019,Waste Atlas Dumpsites,,Pietermaritzburg,KwaZulu-Natal,South Africa,True
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,48900 - 70800,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,78260 - 113000,We need your support,Active,2019,Waste Atlas Dumpsites,,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,189000 - 272000,100,Active,2019,Waste Atlas Dumpsites,,,Eastern Cape,South Africa,False
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,412 - 580,200,Active,2019,Waste Atlas Dumpsites,Epe,Epe,Lagos,Nigeria,True
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,166000 - 240000,670,Active,2019,Waste Atlas Dumpsites,,Bamako,,Mali,True
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,766000 - 1100000,We need your support,Active,2019,Waste Atlas Dumpsites,,Freetown,Western Area Urban,Sierra Leone,True
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,351800 - 350000,18,Active,2019,Waste Atlas Dumpsites,,,,Palestinian Territory,False
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,245900 - 250000,We need your support,Active,2019,Waste Atlas Dumpsites,,دير البلح,,Palestinian Territory,True
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,222300 - 333000,35,Active,2019,Waste Atlas Dumpsites,,Puno,Puno,Perú,True
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,25200 - 36400,100,Active,2019,Waste Atlas Dumpsites,,,Central Equatoria,South Sudan,False
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,95200 - 142800,40,Active,2019,Waste Atlas Dumpsites,,Cusco,Cusco,Perú,True
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,212000 - 303000,100,Active,2019,Waste Atlas Dumpsites,,,Likisá,Timór Lorosa'e / Timor-Leste,False
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,44100 - 63000,70,Active,2019,Waste Atlas Dumpsites,Yura,Yura,Arequipa,Perú,True
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,We need your suppor,We need your suppor,3000,Active,2019,Waste Atlas Dumpsites,,Chinandega,Chinandega,Nicaragua,True
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,Râmnicu Sărat,Râmnicu Sărat,,România,True
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,,Serrekunda,Kanifing,Gambia,True
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,We need your suppor,We need your suppor,We need your support,Active,2019,Waste Atlas Dumpsites,,,Arta عرتا,Djibouti جيبوتي,False
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,We need your suppor,We need your suppor,100,Active,2019,Waste Atlas Dumpsites,San Josecito,San Josecito,Táchira,Venezuela,True
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,We need your suppor,We need your suppor,5,Active,2019,Waste Atlas Dumpsites,Lluyllucucha,Moyobamba,San Martín,Perú,True
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,We need your suppor,We need your suppor,35,Active,2019,Waste Atlas Dumpsites,,,Tumbes,Perú,False
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,We need your suppor,We need your suppor,15-20,Active,2019,Waste Atlas Dumpsites,,Chimbote,Ancash,Perú,True
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,We need your suppor,We need your suppor,70,Active,2019,Waste Atlas Dumpsites,,Castilla,Piura,Perú,True
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,,Juliaca,Puno,Perú,True

In [81]:
#creating an excel file because this code takes a long time to run
df4_clean.to_excel("df_waste_atlas_dumpsites.xlsx") 

df4_clean1 = pd.read_excel('df_waste_atlas_dumpsites.xlsx')

In [82]:
df4_clean1

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,City,state,country,Available City Data
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Estado de México,México,False
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,NaN,Duque de Caxias,Rio de Janeiro,Brasil,True
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,280000 - 400000,3000,Active,2019,Waste Atlas Dumpsites,NaN,Quezon City,NaN,Philippines,True
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,367000 - 523000,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,150000 - 214000,1200,Active,2019,Waste Atlas Dumpsites,NaN,Managua (Municipio),Managua,Nicaragua,True
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,257000 - 360000,5000,Active,2019,Waste Atlas Dumpsites,NaN,Kota Bekasi,Jawa Barat,Indonesia,True
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,NaN,City of New York,New York,United States,True
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,India,False
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,401000 - 573000,1200,Active,2019,Waste Atlas Dumpsites,NaN,Ikeja,Lagos,Nigeria,True
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,90100 - 128000,1500,Active,2019,Waste Atlas Dumpsites,NaN,Mumbai,Maharashtra,India,True
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,22300 - 31900,2000,Active,2019,Waste Atlas Dumpsites,NaN,Port-au-Prince,Département de l'Ouest,Ayiti,True
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,326000 - 466000,420,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,326400 - 466300,2000,Active,2019,Waste Atlas Dumpsites,NaN,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,112000 - 160000,5000,Active,2019,Waste Atlas Dumpsites,NaN,Cochabamba,Cochabamba,Bolivia,True
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,ខណ្ឌមានជ័យ,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,True
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,NaN,Chennai,Tamil Nadu,India,True
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,215600 - 307800,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,لاہور,پنجاب,پاکستان,True
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tamil Nadu,India,False
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,NaN,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,100000 - 150000,200,Active,2019,Waste Atlas Dumpsites,NaN,San Carlos de Bariloche,Río Negro,Argentina,True
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,171000 - 242000,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Україна,False
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,Гаспра,NaN,Україна,True
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,We need you support,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Московская область,Россия,False
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Новосибирск,Новосибирская область,Россия,True
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,NaN,صيدا,محافظة الجنوب,لبنان,True
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,200000 - 286000,1000,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Чүй облусу,Кыргызстан,False
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Mar del Plata,Buenos Aires,Argentina,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,57500 - 82500,50,Active,2019,Waste Atlas Dumpsites,NaN,غزة,NaN,Palestinian Territory,True
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,418750 - 600000,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Pedungan,Bali,Indonesia,True
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,490000 - 700000,150,Active,2019,Waste Atlas Dumpsites,NaN,Krugersdorp,Gauteng,South Africa,True
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,80000 - 127000,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Karnataka,India,False
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,190000 - 270000,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,Градска општина Гроцка,Централна Србија,Србија,True
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,44000 - 58000,30,Active,2019,Waste Atlas Dumpsites,NaN,NaN,المفرق,الأردن,False
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,128000 - 183000,300,Active,2019,Waste Atlas Dumpsites,NaN,Pietermaritzburg,KwaZulu-Natal,South Africa,True
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,48900 - 70800,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,78260 - 113000,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,189000 - 272000,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Eastern Cape,South Africa,False
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,412 - 580,200,Active,2019,Waste Atlas Dumpsites,Epe,Epe,Lagos,Nigeria,True
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,166000 - 240000,670,Active,2019,Waste Atlas Dumpsites,NaN,Bamako,NaN,Mali,True
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,766000 - 1100000,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,Freetown,Western Area Urban,Sierra Leone,True
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,351800 - 350000,18,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Palestinian Territory,False
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,245900 - 250000,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,دير البلح,NaN,Palestinian Territory,True
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,222300 - 333000,35,Active,2019,Waste Atlas Dumpsites,NaN,Puno,Puno,Perú,True
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,25200 - 36400,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Central Equatoria,South Sudan,False
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,95200 - 142800,40,Active,2019,Waste Atlas Dumpsites,NaN,Cusco,Cusco,Perú,True
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,212000 - 303000,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Likisá,Timór Lorosa'e / Timor-Leste,False
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,44100 - 63000,70,Active,2019,Waste Atlas Dumpsites,Yura,Yura,Arequipa,Perú,True
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,We need your suppor,We need your suppor,3000,Active,2019,Waste Atlas Dumpsites,NaN,Chinandega,Chinandega,Nicaragua,True
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,Râmnicu Sărat,Râmnicu Sărat,NaN,România,True
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,We need your suppor,We need your suppor,We need your support,We need your support,2019,Waste Atlas Dumpsites,NaN,Serrekunda,Kanifing,Gambia,True
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,We need your suppor,We need your suppor,We need your support,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Arta عرتا,Djibouti جيبوتي,False
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,We need your suppor,We need your suppor,100,Active,2019,Waste Atlas Dumpsites,San Josecito,San Josecito,Táchira,Venezuela,True
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,We need your suppor,We need your suppor,5,Active,2019,Waste Atlas Dumpsites,Lluyllucucha,Moyobamba,San Martín,Perú,True
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,We need your suppor,We need your suppor,35,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tumbes,Perú,False
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,We need your suppor,We need your suppor,15-20,Active,2019,Waste Atlas Dumpsites,NaN,Chimbote,Ancash,Perú,True
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,We need your suppor,We need your suppor,70,Active,2019,Waste Atlas Dumpsites,NaN,Castilla,Piura,Perú,True
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,NaN,Juliaca,Puno,Perú,True

In [89]:
#We are missing much city data, however Andre was able to give javascript code to fix it, let's count how many need fixed
value_counts = df4_clean1['Available City Data'].value_counts()

# Get the count of "True" and "False"
count_true = value_counts[True]
count_false = value_counts[False]

# Print the counts
print("Count of True:", count_true)
print("Count of False:", count_false)

# True:61
# False: 32

Count of True: 61
Count of False: 32

In [ ]:
# This code was used in google sheets to find cities for the 305 values
'''

function cityOf(geocode) {

  geolat=geocode.split(",")[0]
  geolng=geocode.split(",")[1]

  var city = Maps.newGeocoder().reverseGeocode(geolat,geolng)["results"][0]["address_components"][1]["long_name"];
  var state = Maps.newGeocoder().reverseGeocode(geolat,geolng)["results"][0]["address_components"][3]["short_name"];
  response=city

  return response

  
}

In [64]:
# There are some rows in the waste column that have a string "we need your support". remove them. 
# Define the string to remove
string_to_replace = 'We need your support'
df4_clean1 = df4_clean1.replace(string_to_replace, np.nan)

string_to_replace2 = 'We need you support'
df4_clean1 = df4_clean1.replace(string_to_replace2, np.nan)

string_to_replace3 = 'We need your suppor'
df4_clean1 = df4_clean1.replace(string_to_replace3, np.nan)




# Display the updated DataFrame
df4_clean1

#Now there are 80 rows instead of 93 so we lost 13 datapoints

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,city,state,country,Available City Data,value1,value2
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Estado de México,México,False,88889,88889
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,114286,114286
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,NaN,Duque de Caxias,Rio de Janeiro,Brasil,True,321429,321429
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,"280000 , 400000",3000,Active,2019,Waste Atlas Dumpsites,NaN,Quezon City,NaN,Philippines,True,280000,400000
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,"367000 , 523000",3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True,367000,523000
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,86527,86527
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,"150000 , 214000",1200,Active,2019,Waste Atlas Dumpsites,NaN,Managua (Municipio),Managua,Nicaragua,True,150000,214000
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,"257000 , 360000",5000,Active,2019,Waste Atlas Dumpsites,NaN,Kota Bekasi,Jawa Barat,Indonesia,True,257000,360000
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,NaN,City of New York,New York,United States,True,247191,247191
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,India,False,129630,129630
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,"401000 , 573000",1200,Active,2019,Waste Atlas Dumpsites,NaN,Ikeja,Lagos,Nigeria,True,401000,573000
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,129790,129790
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,"90100 , 128000",1500,Active,2019,Waste Atlas Dumpsites,NaN,Mumbai,Maharashtra,India,True,90100,128000
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,"22300 , 31900",2000,Active,2019,Waste Atlas Dumpsites,NaN,Port-au-Prince,Département de l'Ouest,Ayiti,True,22300,31900
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,"326000 , 466000",420,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,326000,466000
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,"326400 , 466300",2000,Active,2019,Waste Atlas Dumpsites,NaN,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True,326400,466300
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,"112000 , 160000",5000,Active,2019,Waste Atlas Dumpsites,NaN,Cochabamba,Cochabamba,Bolivia,True,112000,160000
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,NaN,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,False,24716,24716
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,NaN,Chennai,Tamil Nadu,India,True,49421,49421
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,"215600 , 307800",NaN,Active,2019,Waste Atlas Dumpsites,NaN,لاہور,پنجاب,پاکستان,True,215600,307800
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tamil Nadu,India,False,49419,49419
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,NaN,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True,130435,130435
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,"100000 , 150000",200,Active,2019,Waste Atlas Dumpsites,NaN,San Carlos de Bariloche,Río Negro,Argentina,True,100000,150000
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,"171000 , 242000",0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Україна,False,171000,242000
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,NaN,NaN,Україна,False,200000,200000
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Московская область,Россия,False,125984,125984
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Новосибирск,Новосибирская область,Россия,True,50000,50000
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,NaN,صيدا,محافظة الجنوب,لبنان,True,217008,217008
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,"200000 , 286000",1000,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Чүй облусу,Кыргызстан,False,200000,286000
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Mar del Plata,Buenos Aires,Argentina,True,192766,192766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,"57500 , 82500",50,Active,2019,Waste Atlas Dumpsites,NaN,غزة,NaN,Palestinian Territory,True,57500,82500
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,"418750 , 600000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Pedungan,Bali,Indonesia,True,418750,600000
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,"490000 , 700000",150,Active,2019,Waste Atlas Dumpsites,NaN,Krugersdorp,Gauteng,South Africa,True,490000,700000
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,"80000 , 127000",0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Karnataka,India,False,80000,127000
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,"190000 , 270000",20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,NaN,Централна Србија,Србија,False,190000,270000
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,"44000 , 58000",30,Active,2019,Waste Atlas Dumpsites,NaN,NaN,المفرق,الأردن,False,44000,58000
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,"128000 , 183000",300,Active,2019,Waste Atlas Dumpsites,NaN,Pietermaritzburg,KwaZulu-Natal,South Africa,True,128000,183000
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,"48900 , 70800",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,48900,70800
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,"78260 , 113000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,78260,113000
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,"189000 , 272000",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Eastern Cape,South Africa,False,189000,272000
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,"412 , 580",200,Active,2019,Waste Atlas Dumpsites,Epe,NaN,Lagos,Nigeria,False,412,580
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,"166000 , 240000",670,Active,2019,Waste Atlas Dumpsites,NaN,Bamako,NaN,Mali,True,166000,240000
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,"766000 , 1100000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Freetown,Western Area Urban,Sierra Leone,True,766000,1100000
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,"351800 , 350000",18,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Palestinian Territory,False,351800,350000
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,"245900 , 250000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,دير البلح,NaN,Palestinian Territory,True,245900,250000
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,"222300 , 333000",35,Active,2019,Waste Atlas Dumpsites,NaN,Puno,Puno,Perú,True,222300,333000
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,"25200 , 36400",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Central Equatoria,South Sudan,False,25200,36400
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,"95200 , 142800",40,Active,2019,Waste Atlas Dumpsites,NaN,Cusco,Cusco,Perú,True,95200,142800
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,"212000 , 303000",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Likisá,Timór Lorosa'e / Timor-Leste,False,212000,303000
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,"44100 , 63000",70,Active,2019,Waste Atlas Dumpsites,Yura,NaN,Arequipa,Perú,False,44100,63000
83,CHINANDEGA BOTADERO,12.620821,-87.143936,Dumpsites,NaN,NaN,3000,Active,2019,Waste Atlas Dumpsites,NaN,Chinandega,Chinandega,Nicaragua,True,NaN,NaN
84,RAMNICU SARAT LANDFILL,45.366776,27.066317,Dumpsites,NaN,NaN,NaN,NaN,2019,Waste Atlas Dumpsites,Râmnicu Sărat,NaN,NaN,România,False,NaN,NaN
85,BAKOTEH DUMPSITE,13.439247,-16.697277,Dumpsites,NaN,NaN,NaN,NaN,2019,Waste Atlas Dumpsites,NaN,Serrekunda,Kanifing,Gambia,True,NaN,NaN
86,DOUDA DUMPSITE,11.523468,43.163899,Dumpsites,NaN,NaN,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Arta عرتا,Djibouti جيبوتي,False,NaN,NaN
87,SAN JOSECITO,7.641020,-72.213210,Dumpsites,NaN,NaN,100,Active,2019,Waste Atlas Dumpsites,San Josecito,NaN,Táchira,Venezuela,False,NaN,NaN
88,MOYOBAMABA DUMPSITE,-5.998400,-76.995720,Dumpsites,NaN,NaN,5,Active,2019,Waste Atlas Dumpsites,Lluyllucucha,Moyobamba,San Martín,Perú,True,NaN,NaN
89,TUMBES DUMPSITE,-3.597980,-80.419300,Dumpsites,NaN,NaN,35,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tumbes,Perú,False,NaN,NaN
90,CHIMBOTE DUMPSITE,-9.038810,-78.609440,Dumpsites,NaN,NaN,15-20,Active,2019,Waste Atlas Dumpsites,NaN,Chimbote,Ancash,Perú,True,NaN,NaN
91,PIURA DUMPSITE,-5.169320,-80.559490,Dumpsites,NaN,NaN,70,Active,2019,Waste Atlas Dumpsites,NaN,Castilla,Piura,Perú,True,NaN,NaN
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,NaN,Juliaca,Puno,Perú,True,136875,136875

In [75]:
#The waste column has two values in some rows, I need to split those up and average them. 
df4_clean1['waste'] = df4_clean1['waste'].astype(str)
df4_clean1['waste'] = df4_clean1['waste'].str.replace('-', ',')

df4_clean1['waste'] = df4_clean1['waste'].str.replace('nan', 'NaN')


# Remove rows containing the string "NaN"
df4_clean1 = df4_clean1[df4_clean1['waste'] != 'NaN']


df4_clean1
# Now there are 80 rows x 17 columns --> so we lost 13 datapoints

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/pandas/core/series.py:3893: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(result)

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,city,state,country,Available City Data,value1,value2
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889,1500,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Estado de México,México,False,88889,88889
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,114286,114286
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429,1700,Inactive,2019,Waste Atlas Dumpsites,NaN,Duque de Caxias,Rio de Janeiro,Brasil,True,321429,321429
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,"280000 , 400000",3000,Active,2019,Waste Atlas Dumpsites,NaN,Quezon City,NaN,Philippines,True,280000,400000
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,"367000 , 523000",3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True,367000,523000
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,86527,86527
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,"150000 , 214000",1200,Active,2019,Waste Atlas Dumpsites,NaN,Managua (Municipio),Managua,Nicaragua,True,150000,214000
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,"257000 , 360000",5000,Active,2019,Waste Atlas Dumpsites,NaN,Kota Bekasi,Jawa Barat,Indonesia,True,257000,360000
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191,0,Inactive,2019,Waste Atlas Dumpsites,NaN,City of New York,New York,United States,True,247191,247191
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,India,False,129630,129630
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,"401000 , 573000",1200,Active,2019,Waste Atlas Dumpsites,NaN,Ikeja,Lagos,Nigeria,True,401000,573000
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,129790,129790
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,"90100 , 128000",1500,Active,2019,Waste Atlas Dumpsites,NaN,Mumbai,Maharashtra,India,True,90100,128000
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,"22300 , 31900",2000,Active,2019,Waste Atlas Dumpsites,NaN,Port-au-Prince,Département de l'Ouest,Ayiti,True,22300,31900
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,"326000 , 466000",420,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,326000,466000
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,"326400 , 466300",2000,Active,2019,Waste Atlas Dumpsites,NaN,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True,326400,466300
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,"112000 , 160000",5000,Active,2019,Waste Atlas Dumpsites,NaN,Cochabamba,Cochabamba,Bolivia,True,112000,160000
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,NaN,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,False,24716,24716
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421,2000,Active,2019,Waste Atlas Dumpsites,NaN,Chennai,Tamil Nadu,India,True,49421,49421
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,"215600 , 307800",NaN,Active,2019,Waste Atlas Dumpsites,NaN,لاہور,پنجاب,پاکستان,True,215600,307800
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tamil Nadu,India,False,49419,49419
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435,0,Inactive,2019,Waste Atlas Dumpsites,NaN,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True,130435,130435
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,"100000 , 150000",200,Active,2019,Waste Atlas Dumpsites,NaN,San Carlos de Bariloche,Río Negro,Argentina,True,100000,150000
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,"171000 , 242000",0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Україна,False,171000,242000
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000,0,Active,2019,Waste Atlas Dumpsites,Гаспра,NaN,NaN,Україна,False,200000,200000
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Московская область,Россия,False,125984,125984
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Новосибирск,Новосибирская область,Россия,True,50000,50000
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008,12,Active,2019,Waste Atlas Dumpsites,NaN,صيدا,محافظة الجنوب,لبنان,True,217008,217008
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,"200000 , 286000",1000,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Чүй облусу,Кыргызстан,False,200000,286000
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Mar del Plata,Buenos Aires,Argentina,True,192766,192766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,SOLOUS,6.570992,3.253803,Dumpsites,1591459,83761,NaN,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False,83761,83761
55,SOLOUS 2,6.571507,3.251759,Dumpsites,4000000 - 5750000,"512000 , 737000",350 - 400,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False,512000,737000
56,AGBOGBLOSHIE,5.553956,-0.227229,Dumpsites,1750000 - 2500000,"165000 , 235000",10000,Active,2019,Waste Atlas Dumpsites,NaN,Accra,Greater Accra Region,Ghana,True,165000,235000
57,ESTRUTURAL,-15.765128,-48.001059,Dumpsites,21000000 - 30000000,"154000 , 220000",2500,Active,2019,Waste Atlas Dumpsites,SCIA,NaN,Distrito Federal,Brasil,False,154000,220000
58,REQUE,-6.907469,-79.768766,Dumpsites,4000000 - 5700000,"17000 , 24250",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lambayeque,Perú,False,17000,24250
59,HULENE,-25.900193,32.597962,Dumpsites,1750000 - 2500000,"12000 , 147000",500,Active,2019,Waste Atlas Dumpsites,NaN,Cidade de Maputo,NaN,Moçambique,True,12000,147000
60,PUGU KINYAMWEZI,-6.928540,39.131933,Dumpsites,1400000 - 2050000,"21000 , 315000",3000,Active,2019,Waste Atlas Dumpsites,NaN,Dar es Salaam,NaN,Tanzania,True,21000,315000
61,KIBARANI DUMPSITE,-4.033322,39.648237,Dumpsites,2450000 - 3500000,"253000 , 362000",1000,Active,2019,Waste Atlas Dumpsites,NaN,Mombasa,Mombasa,Kenya,True,253000,362000
62,EL MILAGRO,-8.027461,-79.046237,Dumpsites,2000000 - 2900000,"34400 , 50000",100,Active,2019,Waste Atlas Dumpsites,El Milagro,NaN,La Libertad,Perú,False,34400,50000
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,"57500 , 82500",50,Active,2019,Waste Atlas Dumpsites,NaN,غزة,NaN,Palestinian Territory,True,57500,82500
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,"418750 , 600000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Pedungan,Bali,Indonesia,True,418750,600000
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,"490000 , 700000",150,Active,2019,Waste Atlas Dumpsites,NaN,Krugersdorp,Gauteng,South Africa,True,490000,700000
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,"80000 , 127000",0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Karnataka,India,False,80000,127000
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,"190000 , 270000",20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,NaN,Централна Србија,Србија,False,190000,270000
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,"44000 , 58000",30,Active,2019,Waste Atlas Dumpsites,NaN,NaN,المفرق,الأردن,False,44000,58000
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,"128000 , 183000",300,Active,2019,Waste Atlas Dumpsites,NaN,Pietermaritzburg,KwaZulu-Natal,South Africa,True,128000,183000
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,"48900 , 70800",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,48900,70800
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,"78260 , 113000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,78260,113000
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,"189000 , 272000",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Eastern Cape,South Africa,False,189000,272000
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,"412 , 580",200,Active,2019,Waste Atlas Dumpsites,Epe,NaN,Lagos,Nigeria,False,412,580
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,"166000 , 240000",670,Active,2019,Waste Atlas Dumpsites,NaN,Bamako,NaN,Mali,True,166000,240000
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,"766000 , 1100000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,Freetown,Western Area Urban,Sierra Leone,True,766000,1100000
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,"351800 , 350000",18,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Palestinian Territory,False,351800,350000
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,"245900 , 250000",NaN,Active,2019,Waste Atlas Dumpsites,NaN,دير البلح,NaN,Palestinian Territory,True,245900,250000
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,"222300 , 333000",35,Active,2019,Waste Atlas Dumpsites,NaN,Puno,Puno,Perú,True,222300,333000
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,"25200 , 36400",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Central Equatoria,South Sudan,False,25200,36400
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,"95200 , 142800",40,Active,2019,Waste Atlas Dumpsites,NaN,Cusco,Cusco,Perú,True,95200,142800
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,"212000 , 303000",100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Likisá,Timór Lorosa'e / Timor-Leste,False,212000,303000
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,"44100 , 63000",70,Active,2019,Waste Atlas Dumpsites,Yura,NaN,Arequipa,Perú,False,44100,63000
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875,0,Active,2019,Waste Atlas Dumpsites,NaN,Juliaca,Puno,Perú,True,136875,136875

In [76]:
# Calculate the average

df4_clean1[['value1', 'value2']] = df4_clean1['waste'].str.split(',', expand=True)
df4_clean1['value2'] = df4_clean1['value2'].fillna(df4_clean1['value1'])

# now we have two columns, but the 'value2' column has a few NAs which need to be filled

df4_clean1['value1'] = df4_clean1['value1'].astype(int)
df4_clean1['value2'] = df4_clean1['value2'].astype(int)

# now we can average them
df4_clean1['waste'] = (df4_clean1['value1'] + df4_clean1['value2']) / 2


df4_clean1

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]
/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,city,state,country,Available City Data,value1,value2
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889.0,1500,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Estado de México,México,False,88889,88889
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,114286,114286
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429.0,1700,Inactive,2019,Waste Atlas Dumpsites,NaN,Duque de Caxias,Rio de Janeiro,Brasil,True,321429,321429
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,340000.0,3000,Active,2019,Waste Atlas Dumpsites,NaN,Quezon City,NaN,Philippines,True,280000,400000
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,445000.0,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True,367000,523000
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False,86527,86527
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,182000.0,1200,Active,2019,Waste Atlas Dumpsites,NaN,Managua (Municipio),Managua,Nicaragua,True,150000,214000
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,308500.0,5000,Active,2019,Waste Atlas Dumpsites,NaN,Kota Bekasi,Jawa Barat,Indonesia,True,257000,360000
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,City of New York,New York,United States,True,247191,247191
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,India,False,129630,129630
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,487000.0,1200,Active,2019,Waste Atlas Dumpsites,NaN,Ikeja,Lagos,Nigeria,True,401000,573000
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,129790,129790
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,109050.0,1500,Active,2019,Waste Atlas Dumpsites,NaN,Mumbai,Maharashtra,India,True,90100,128000
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,27100.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Port-au-Prince,Département de l'Ouest,Ayiti,True,22300,31900
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,396000.0,420,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False,326000,466000
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,396350.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True,326400,466300
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,136000.0,5000,Active,2019,Waste Atlas Dumpsites,NaN,Cochabamba,Cochabamba,Bolivia,True,112000,160000
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716.0,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,NaN,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,False,24716,24716
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Chennai,Tamil Nadu,India,True,49421,49421
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,261700.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,لاہور,پنجاب,پاکستان,True,215600,307800
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tamil Nadu,India,False,49419,49419
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True,130435,130435
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,125000.0,200,Active,2019,Waste Atlas Dumpsites,NaN,San Carlos de Bariloche,Río Negro,Argentina,True,100000,150000
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,206500.0,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Україна,False,171000,242000
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000.0,0,Active,2019,Waste Atlas Dumpsites,Гаспра,NaN,NaN,Україна,False,200000,200000
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Московская область,Россия,False,125984,125984
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Новосибирск,Новосибирская область,Россия,True,50000,50000
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008.0,12,Active,2019,Waste Atlas Dumpsites,NaN,صيدا,محافظة الجنوب,لبنان,True,217008,217008
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,243000.0,1000,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Чүй облусу,Кыргызстан,False,200000,286000
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Mar del Plata,Buenos Aires,Argentina,True,192766,192766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,SOLOUS,6.570992,3.253803,Dumpsites,1591459,83761.0,NaN,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False,83761,83761
55,SOLOUS 2,6.571507,3.251759,Dumpsites,4000000 - 5750000,624500.0,350 - 400,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False,512000,737000
56,AGBOGBLOSHIE,5.553956,-0.227229,Dumpsites,1750000 - 2500000,200000.0,10000,Active,2019,Waste Atlas Dumpsites,NaN,Accra,Greater Accra Region,Ghana,True,165000,235000
57,ESTRUTURAL,-15.765128,-48.001059,Dumpsites,21000000 - 30000000,187000.0,2500,Active,2019,Waste Atlas Dumpsites,SCIA,NaN,Distrito Federal,Brasil,False,154000,220000
58,REQUE,-6.907469,-79.768766,Dumpsites,4000000 - 5700000,20625.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lambayeque,Perú,False,17000,24250
59,HULENE,-25.900193,32.597962,Dumpsites,1750000 - 2500000,79500.0,500,Active,2019,Waste Atlas Dumpsites,NaN,Cidade de Maputo,NaN,Moçambique,True,12000,147000
60,PUGU KINYAMWEZI,-6.928540,39.131933,Dumpsites,1400000 - 2050000,168000.0,3000,Active,2019,Waste Atlas Dumpsites,NaN,Dar es Salaam,NaN,Tanzania,True,21000,315000
61,KIBARANI DUMPSITE,-4.033322,39.648237,Dumpsites,2450000 - 3500000,307500.0,1000,Active,2019,Waste Atlas Dumpsites,NaN,Mombasa,Mombasa,Kenya,True,253000,362000
62,EL MILAGRO,-8.027461,-79.046237,Dumpsites,2000000 - 2900000,42200.0,100,Active,2019,Waste Atlas Dumpsites,El Milagro,NaN,La Libertad,Perú,False,34400,50000
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,70000.0,50,Active,2019,Waste Atlas Dumpsites,NaN,غزة,NaN,Palestinian Territory,True,57500,82500
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,509375.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Pedungan,Bali,Indonesia,True,418750,600000
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,595000.0,150,Active,2019,Waste Atlas Dumpsites,NaN,Krugersdorp,Gauteng,South Africa,True,490000,700000
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,103500.0,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Karnataka,India,False,80000,127000
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,230000.0,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,NaN,Централна Србија,Србија,False,190000,270000
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,51000.0,30,Active,2019,Waste Atlas Dumpsites,NaN,NaN,المفرق,الأردن,False,44000,58000
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,155500.0,300,Active,2019,Waste Atlas Dumpsites,NaN,Pietermaritzburg,KwaZulu-Natal,South Africa,True,128000,183000
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,59850.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,48900,70800
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,95630.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True,78260,113000
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,230500.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Eastern Cape,South Africa,False,189000,272000
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,496.0,200,Active,2019,Waste Atlas Dumpsites,Epe,NaN,Lagos,Nigeria,False,412,580
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,203000.0,670,Active,2019,Waste Atlas Dumpsites,NaN,Bamako,NaN,Mali,True,166000,240000
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,933000.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Freetown,Western Area Urban,Sierra Leone,True,766000,1100000
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,350900.0,18,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Palestinian Territory,False,351800,350000
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,247950.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,دير البلح,NaN,Palestinian Territory,True,245900,250000
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,277650.0,35,Active,2019,Waste Atlas Dumpsites,NaN,Puno,Puno,Perú,True,222300,333000
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,30800.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Central Equatoria,South Sudan,False,25200,36400
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,119000.0,40,Active,2019,Waste Atlas Dumpsites,NaN,Cusco,Cusco,Perú,True,95200,142800
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,257500.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Likisá,Timór Lorosa'e / Timor-Leste,False,212000,303000
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,53550.0,70,Active,2019,Waste Atlas Dumpsites,Yura,NaN,Arequipa,Perú,False,44100,63000
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875.0,0,Active,2019,Waste Atlas Dumpsites,NaN,Juliaca,Puno,Perú,True,136875,136875

In [77]:
df4_clean1 = df4_clean1.drop(columns=['value1', 'value2'])
df4_clean1 

#final has 80 rows x 11 columns

,asset_id,latitude,longitude,category,Estimated amount of included waste,waste,Informal Sector,Status,Year,Data Source,town,city,state,country,Available City Data
0,BORDO PONIENTE,19.452996,-99.016299,Dumpsites,40000000,88889.0,1500,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Estado de México,México,False
1,CLUJ NAPOCA,46.765104,23.687274,Dumpsites,1600000,114286.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False
2,JARDIM GRAMACHO,-22.748906,-43.258978,Dumpsites,45000000,321429.0,1700,Inactive,2019,Waste Atlas Dumpsites,NaN,Duque de Caxias,Rio de Janeiro,Brasil,True
3,PAYATAS,14.714258,121.106758,Dumpsites,7200000 - 10300000,340000.0,3000,Active,2019,Waste Atlas Dumpsites,NaN,Quezon City,NaN,Philippines,True
4,DANDORA MUNICIPAL DUMPING SITE,-1.249266,36.895381,Dumpsites,19500000 - 27750000,445000.0,3000,Active,2019,Waste Atlas Dumpsites,Babadogo,Nairobi,Nairobi,Kenya,True
5,ORADEA,47.109640,21.857021,Dumpsites,1400000,86527.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,România,False
6,LA CHURECA,12.165855,-86.303315,Dumpsites,6300000 - 9000000,182000.0,1200,Active,2019,Waste Atlas Dumpsites,NaN,Managua (Municipio),Managua,Nicaragua,True
7,BANTAR GEBANG,-6.347886,106.997008,Dumpsites,28280000 - 40400000,308500.0,5000,Active,2019,Waste Atlas Dumpsites,NaN,Kota Bekasi,Jawa Barat,Indonesia,True
8,FRESH KILLS,40.576303,-74.174194,Dumpsites,220000000,247191.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,City of New York,New York,United States,True
9,OKHLA,28.323740,77.178172,Dumpsites,7000000,129630.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,India,False
10,OLUSHOSUN,6.592725,3.378510,Dumpsites,17150000 - 24500000,487000.0,1200,Active,2019,Waste Atlas Dumpsites,NaN,Ikeja,Lagos,Nigeria,True
11,BHALASWA,28.740420,77.157412,Dumpsites,2100000,129790.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False
12,DEONAR,19.072319,72.926774,Dumpsites,11900000 - 17000000,109050.0,1500,Active,2019,Waste Atlas Dumpsites,NaN,Mumbai,Maharashtra,India,True
13,TRUTIER,18.610194,-72.334038,Dumpsites,2100000 - 3000000,27100.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Port-au-Prince,Département de l'Ouest,Ayiti,True
14,GHAZIPUR,28.625025,77.327442,Dumpsites,9800000 - 14000000,396000.0,420,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Delhi,India,False
15,EL TREBOL,14.627313,-90.532751,Dumpsites,6300000 - 9000000,396350.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Ciudad de Guatemala,Departamento de Guatemala,Guatemala,True
16,K'ARA K'ARA,-17.477287,-66.124387,Dumpsites,2800000 - 4000000,136000.0,5000,Active,2019,Waste Atlas Dumpsites,NaN,Cochabamba,Cochabamba,Bolivia,True
17,STUNG MEANCHEY,11.534062,104.897633,Dumpsites,1000000,24716.0,2000,Active,2019,Waste Atlas Dumpsites,ខណ្ឌមានជ័យ,NaN,រាជធានីភ្នំពេញ,ព្រះរាជាណាចក្រ​កម្ពុជា,False
18,KODUNGAIYUR,13.134358,80.268474,Dumpsites,7000000,49421.0,2000,Active,2019,Waste Atlas Dumpsites,NaN,Chennai,Tamil Nadu,India,True
19,MEHMOOD BOOTI,31.609972,74.386883,Dumpsites,5500000 - 7850000,261700.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,لاہور,پنجاب,پاکستان,True
20,PERUGUNDI,12.954919,80.223928,Dumpsites,4000000,49419.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Tamil Nadu,India,False
21,SKAFIDARAS,35.328492,25.050834,Dumpsites,1200000,130435.0,0,Inactive,2019,Waste Atlas Dumpsites,NaN,Δημοτική Ενότητα Γαζίου,Αποκεντρωμένη Διοίκηση Κρήτης,Ελλάς,True
22,BARILOCHE,-41.175036,-71.355000,Dumpsites,1000000 - 1500000,125000.0,200,Active,2019,Waste Atlas Dumpsites,NaN,San Carlos de Bariloche,Río Negro,Argentina,True
23,ALUSHTA,44.721918,34.434865,Dumpsites,600000 - 850000,206500.0,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Україна,False
24,GASPRA,44.449406,34.106669,Dumpsites,1200000,200000.0,0,Active,2019,Waste Atlas Dumpsites,Гаспра,NaN,NaN,Україна,False
25,IKSHA,56.206907,37.415271,Dumpsites,8000000,125984.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Московская область,Россия,False
26,NOVOSIBIRSK,55.052969,83.073099,Dumpsites,2000000,50000.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Новосибирск,Новосибирская область,Россия,True
27,SIDON,33.550265,35.364561,Dumpsites,1200000,217008.0,12,Active,2019,Waste Atlas Dumpsites,NaN,صيدا,محافظة الجنوب,لبنان,True
28,BISHEK DUMPSITE,42.967222,74.588958,Dumpsites,7700000 - 11000000,243000.0,1000,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Чүй облусу,Кыргызстан,False
29,PREDIO,-38.075289,-57.650661,Dumpsites,3084250,192766.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Mar del Plata,Buenos Aires,Argentina,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,SOLOUS,6.570992,3.253803,Dumpsites,1591459,83761.0,NaN,Inactive,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False
55,SOLOUS 2,6.571507,3.251759,Dumpsites,4000000 - 5750000,624500.0,350 - 400,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lagos,Nigeria,False
56,AGBOGBLOSHIE,5.553956,-0.227229,Dumpsites,1750000 - 2500000,200000.0,10000,Active,2019,Waste Atlas Dumpsites,NaN,Accra,Greater Accra Region,Ghana,True
57,ESTRUTURAL,-15.765128,-48.001059,Dumpsites,21000000 - 30000000,187000.0,2500,Active,2019,Waste Atlas Dumpsites,SCIA,NaN,Distrito Federal,Brasil,False
58,REQUE,-6.907469,-79.768766,Dumpsites,4000000 - 5700000,20625.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Lambayeque,Perú,False
59,HULENE,-25.900193,32.597962,Dumpsites,1750000 - 2500000,79500.0,500,Active,2019,Waste Atlas Dumpsites,NaN,Cidade de Maputo,NaN,Moçambique,True
60,PUGU KINYAMWEZI,-6.928540,39.131933,Dumpsites,1400000 - 2050000,168000.0,3000,Active,2019,Waste Atlas Dumpsites,NaN,Dar es Salaam,NaN,Tanzania,True
61,KIBARANI DUMPSITE,-4.033322,39.648237,Dumpsites,2450000 - 3500000,307500.0,1000,Active,2019,Waste Atlas Dumpsites,NaN,Mombasa,Mombasa,Kenya,True
62,EL MILAGRO,-8.027461,-79.046237,Dumpsites,2000000 - 2900000,42200.0,100,Active,2019,Waste Atlas Dumpsites,El Milagro,NaN,La Libertad,Perú,False
63,JOHR AL DEEK,31.457550,34.452937,Dumpsites,1150000 - 1650000,70000.0,50,Active,2019,Waste Atlas Dumpsites,NaN,غزة,NaN,Palestinian Territory,True
64,SUWUNG DUMP,-8.721798,115.220215,Dumpsites,6700000 - 9600000,509375.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Pedungan,Bali,Indonesia,True
65,LUIPAARDSVLEI,-26.120061,27.786166,Dumpsites,2450000 - 3500000,595000.0,150,Active,2019,Waste Atlas Dumpsites,NaN,Krugersdorp,Gauteng,South Africa,True
66,BRUHAT BANAGLORE MAHANAGARA PALIKE (BBMP) (MA...,13.084375,77.725784,Dumpsites,2800000 - 3950000,103500.0,0,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Karnataka,India,False
67,VINČA,44.786406,20.599512,Dumpsites,6650000 - 9500000,230000.0,20,Active,2019,Waste Atlas Dumpsites,Градска општина Гроцка,NaN,Централна Србија,Србија,False
68,AL HUSAINEYAT,32.255928,36.349202,Dumpsites,1250000 - 1650000,51000.0,30,Active,2019,Waste Atlas Dumpsites,NaN,NaN,المفرق,الأردن,False
69,NEW ENGLAND ROAD WASTE DUMPSITE,-29.606424,30.419801,Dumpsites,2450000 - 3500000,155500.0,300,Active,2019,Waste Atlas Dumpsites,NaN,Pietermaritzburg,KwaZulu-Natal,South Africa,True
70,HTAIN BIN DUMPSITE,16.897999,96.021095,Dumpsites,2350000 - 3400000,59850.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
71,HTWEI CHAUNG,16.918785,96.183778,Dumpsites,1800000 - 2600000,95630.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Yangon,ရန်ကုန်တိုင်းဒေသကြီး,မြန်မာ,True
72,ARLINGTON WASTE DUMPSITE,-34.013325,25.572207,Dumpsites,2500000 - 3600000,230500.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Eastern Cape,South Africa,False
73,EPE,6.649220,4.038162,Dumpsites,33000 - 47000,496.0,200,Active,2019,Waste Atlas Dumpsites,Epe,NaN,Lagos,Nigeria,False
74,DOUMANZANA DUMP,12.681867,-7.937742,Dumpsites,1250000 - 1800000,203000.0,670,Active,2019,Waste Atlas Dumpsites,NaN,Bamako,NaN,Mali,True
75,GRANVILLE BROOK DUMPSITE (KISSY DUMPSITE),8.482030,-13.209562,Dumpsites,2300000 - 3300000,933000.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,Freetown,Western Area Urban,Sierra Leone,True
76,SOFA LANDFILL (RAFAH MUNICIPALITY LANDFILL),31.270774,34.327700,Dumpsites,650000 - 950000,350900.0,18,Active,2019,Waste Atlas Dumpsites,NaN,NaN,NaN,Palestinian Territory,False
77,DEIR AL BALAH,31.392287,34.381940,Dumpsites,1000000 - 1500000,247950.0,NaN,Active,2019,Waste Atlas Dumpsites,NaN,دير البلح,NaN,Palestinian Territory,True
78,CANCHARANI,-15.892261,-70.028369,Dumpsites,1000000 - 1500000,277650.0,35,Active,2019,Waste Atlas Dumpsites,NaN,Puno,Puno,Perú,True
79,LAGOON DUMP SITE,4.827500,31.505699,Dumpsites,630000 - 910000,30800.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Central Equatoria,South Sudan,False
80,JAQUIRA (HAQUIRA),-13.552149,-72.017254,Dumpsites,1000000 - 1500000,119000.0,40,Active,2019,Waste Atlas Dumpsites,NaN,Cusco,Cusco,Perú,True
81,TIBAR LANDFILL,-8.577469,125.500252,Dumpsites,770000 - 1100000,257500.0,100,Active,2019,Waste Atlas Dumpsites,NaN,NaN,Likisá,Timór Lorosa'e / Timor-Leste,False
82,QUEBRADA HONDA ISPAMPA YURA,-16.272276,-71.647440,Dumpsites,450000 - 630000,53550.0,70,Active,2019,Waste Atlas Dumpsites,Yura,NaN,Arequipa,Perú,False
92,JULIACA DUMPSITE,-15.499270,-70.102960,Dumpsites,273750,136875.0,0,Active,2019,Waste Atlas Dumpsites,NaN,Juliaca,Puno,Perú,True

In [90]:
df4_clean1.to_excel("df_waste_atlas_dumpsites_final.xlsx")

In [ ]:
# lets clean df5

In [22]:
df5

,name,lat,lng,category,Status,Area,Amount of waste disposed,Annual capacity,Population served,Data Source
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Climate Trace
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Climate Trace
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Climate Trace
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Climate Trace
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Climate Trace
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Climate Trace
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Climate Trace
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Climate Trace
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Climate Trace
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Climate Trace
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Climate Trace
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Climate Trace
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Climate Trace
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Climate Trace
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Climate Trace
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Climate Trace
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Climate Trace
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Climate Trace
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Climate Trace
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Climate Trace
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Climate Trace
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Climate Trace
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Climate Trace
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Climate Trace
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Climate Trace
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Climate Trace
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Climate Trace
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Climate Trace
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Climate Trace
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Climate Trace
...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,We need your support,Climate Trace
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,We need your support,Climate Trace
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,We need your support,Climate Trace
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,We need your support,Climate Trace
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,We need your support,Climate Trace
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,We need your support,Climate Trace
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,We need your support,Climate Trace
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,We need your support,Climate Trace
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,We need your support,Climate Trace
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,We need your support,Climate Trace
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,We need your support,Climate Trace
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,We need your support,Climate Trace
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,We need your support,Climate Trace
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,We need your support,Climate Trace
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,We need your support,Climate Trace
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,We need your support,Climate Trace
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,We need your support,Climate Trace
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,We need your support,Climate Trace
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,We need your support,Climate Trace
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,We need your support,Climate Trace
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,We need your support,Climate Trace
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,We need your support,Climate Trace
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,We need your support,Climate Trace
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Climate Trace
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,We need your support,Climate Trace
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,We need your support,Climate Trace
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Climate Trace
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,We need your support,Climate Trace
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,We need your support,Climate Trace
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Climate Trace

In [24]:
# Now lets clean the df5 dataset
df5['Year'] = '2015'
df5['Data Source'] = 'Waste Atlas Landfills'

df5_clean = df5
df5_clean.rename(columns={'name':'asset_id', 'lat':'latitude', 'lng': 'longitude', 
                    'Amount of waste disposed': 'waste', 'Population served': 'population'
                   }, inplace=True)

df5_clean
#final has 569 rows × 10 columns

,asset_id,latitude,longitude,category,Status,Area,waste,Annual capacity,population,Data Source,Year
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Waste Atlas Landfills,2019
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Waste Atlas Landfills,2019
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Waste Atlas Landfills,2019
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Waste Atlas Landfills,2019
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Waste Atlas Landfills,2019
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Waste Atlas Landfills,2019
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Waste Atlas Landfills,2019
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Waste Atlas Landfills,2019
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Waste Atlas Landfills,2019
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Waste Atlas Landfills,2019
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Waste Atlas Landfills,2019
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Waste Atlas Landfills,2019
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Waste Atlas Landfills,2019
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Waste Atlas Landfills,2019
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Waste Atlas Landfills,2019
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Waste Atlas Landfills,2019
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Waste Atlas Landfills,2019
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Waste Atlas Landfills,2019
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Waste Atlas Landfills,2019
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Waste Atlas Landfills,2019
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Waste Atlas Landfills,2019
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Waste Atlas Landfills,2019
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Waste Atlas Landfills,2019
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Waste Atlas Landfills,2019
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Waste Atlas Landfills,2019
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Waste Atlas Landfills,2019
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Waste Atlas Landfills,2019
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Waste Atlas Landfills,2019
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Waste Atlas Landfills,2019
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Waste Atlas Landfills,2019
...,...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,We need your support,Waste Atlas Landfills,2019
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,We need your support,Waste Atlas Landfills,2019
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,We need your support,Waste Atlas Landfills,2019
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,We need your support,Waste Atlas Landfills,2019
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,We need your support,Waste Atlas Landfills,2019
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,We need your support,Waste Atlas Landfills,2019
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,We need your support,Waste Atlas Landfills,2019
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,We need your support,Waste Atlas Landfills,2019
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,We need your support,Waste Atlas Landfills,2019
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,We need your support,Waste Atlas Landfills,2019
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,We need your support,Waste Atlas Landfills,2019
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,We need your support,Waste Atlas Landfills,2019
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,We need your support,Waste Atlas Landfills,2019
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,We need your support,Waste Atlas Landfills,2019
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,We need your support,Waste Atlas Landfills,2019
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,We need your support,Waste Atlas Landfills,2019
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,We need your support,Waste Atlas Landfills,2019
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,We need your support,Waste Atlas Landfills,2019
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,We need your support,Waste Atlas Landfills,2019
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,We need your support,Waste Atlas Landfills,2019
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,We need your support,Waste Atlas Landfills,2019
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,We need your support,Waste Atlas Landfills,2019
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,We need your support,Waste Atlas Landfills,2019
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,We need your support,Waste Atlas Landfills,2019
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,We need your support,Waste Atlas Landfills,2019
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,We need your support,Waste Atlas Landfills,2019
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,We need your support,Waste Atlas Landfills,2019
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Waste Atlas Landfills,2019

In [26]:

#!pip install geopy
#import geopy
#from geopy.geocoders import Nominatim

# Create a geocoder instance
geolocator = Nominatim(user_agent="my_geocoder")

# Reverse geocode to get the city name
#df4_clean['city'] = df4_clean.apply(lambda row: geolocator.reverse(f"{row['latitude']}, {row['longitude']}").raw['address'].get('city', ''), axis=1)




def town_city_state_country(row):
    coord = f"{row['latitude']}, {row['longitude']}"
    location = geolocator.reverse(coord, exactly_one=True, timeout=None)
    address = location.raw['address']
    city = address.get('city', '')
    state = address.get('state', '')
    country = address.get('country', '')
    town = address.get('town', '')
    row['town'] = town
    row['city'] = city
    row['state'] = state
    row['country'] = country
    
    return row

df5_clean = df5_clean.apply(town_city_state_country, axis=1)
df5_clean

,asset_id,latitude,longitude,category,Status,Area,waste,Annual capacity,population,Data Source,Year,town,city,state,country
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Waste Atlas Landfills,2019,,乌当区,贵州省,中国
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Waste Atlas Landfills,2019,,Caucaia,Ceará,Brasil
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Waste Atlas Landfills,2019,,São Paulo,São Paulo,Brasil
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Waste Atlas Landfills,2019,,Campinas,São Paulo,Brasil
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Waste Atlas Landfills,2019,,,Buenos Aires,Argentina
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Waste Atlas Landfills,2019,,Ciudad López Mateos,Estado de México,México
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Waste Atlas Landfills,2019,,Contagem,Minas Gerais,Brasil
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Waste Atlas Landfills,2019,,Valparaíso,Región de Valparaíso,Chile
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Waste Atlas Landfills,2019,,Perímetro Urbano Medellín,Antioquia,Colombia
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Waste Atlas Landfills,2019,,,,대한민국
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Waste Atlas Landfills,2019,,강릉시,,대한민국
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Waste Atlas Landfills,2019,,,Дніпропетровська область,Україна
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Waste Atlas Landfills,2019,,朝阳区,北京市,中国
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Waste Atlas Landfills,2019,,Gliwice,województwo śląskie,Polska
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Waste Atlas Landfills,2019,,Rio de Janeiro,Rio de Janeiro,Brasil
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Waste Atlas Landfills,2019,,Goiânia,Goiás,Brasil
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Waste Atlas Landfills,2019,,Feira de Santana,Bahia,Brasil
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Waste Atlas Landfills,2019,,,Región Metropolitana de Santiago,Chile
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Waste Atlas Landfills,2019,,Zapopan,Jalisco,México
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Waste Atlas Landfills,2019,,,województwo warmińsko-mazurskie,Polska
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Waste Atlas Landfills,2019,Końskie,,województwo świętokrzyskie,Polska
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Waste Atlas Landfills,2019,,,województwo mazowieckie,Polska
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Waste Atlas Landfills,2019,,Chorzów,województwo śląskie,Polska
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Waste Atlas Landfills,2019,,,województwo dolnośląskie,Polska
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Waste Atlas Landfills,2019,,Општина Горњи Милановац,Централна Србија,Србија
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Waste Atlas Landfills,2019,,Jastrzębie-Zdrój,województwo śląskie,Polska
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Waste Atlas Landfills,2019,孤店子镇,新北街道,吉林省,中国
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Waste Atlas Landfills,2019,,,Московская область,Россия
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Waste Atlas Landfills,2019,,,Alba / Scotland,United Kingdom
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Waste Atlas Landfills,2019,,,Washington,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,We need your support,Waste Atlas Landfills,2019,,Johnson City,Tennessee,United States
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,We need your support,Waste Atlas Landfills,2019,Loudon,,Tennessee,United States
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,We need your support,Waste Atlas Landfills,2019,Pigeon Forge,,Tennessee,United States
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,We need your support,Waste Atlas Landfills,2019,Menomonee Falls,,Wisconsin,United States
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,We need your support,Waste Atlas Landfills,2019,將軍澳 Tseung Kwan O,西貢區 Sai Kung District,香港 Hong Kong,中国
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,We need your support,Waste Atlas Landfills,2019,,元朗區 Yuen Long District,香港 Hong Kong,中国
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Waste Atlas Landfills,2019,,,Kweneng District,Botswana

In [83]:
# there are still some values missing, but the info in the 'town' column is also a city, so let's replace it.
# Replace blank values in 'city' column with values from 'state' column



df5_clean.city.replace('',df5_clean.town,inplace=True)


df5_clean.rename(columns={'city':'City'
                   }, inplace=True)
df5_clean

,asset_id,latitude,longitude,category,Status,Area,waste,Annual capacity,population,Data Source,Year,town,City,state,country,Available City Data
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Waste Atlas Landfills,2019,,乌当区,贵州省,中国,True
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Waste Atlas Landfills,2019,,Caucaia,Ceará,Brasil,True
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Waste Atlas Landfills,2019,,São Paulo,São Paulo,Brasil,True
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Waste Atlas Landfills,2019,,Campinas,São Paulo,Brasil,True
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Waste Atlas Landfills,2019,,,Buenos Aires,Argentina,False
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Waste Atlas Landfills,2019,,Ciudad López Mateos,Estado de México,México,True
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Waste Atlas Landfills,2019,,Contagem,Minas Gerais,Brasil,True
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Waste Atlas Landfills,2019,,Valparaíso,Región de Valparaíso,Chile,True
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Waste Atlas Landfills,2019,,Perímetro Urbano Medellín,Antioquia,Colombia,True
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Waste Atlas Landfills,2019,,,,대한민국,False
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Waste Atlas Landfills,2019,,강릉시,,대한민국,True
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Waste Atlas Landfills,2019,,,Дніпропетровська область,Україна,False
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Waste Atlas Landfills,2019,,朝阳区,北京市,中国,True
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Waste Atlas Landfills,2019,,Gliwice,województwo śląskie,Polska,True
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Waste Atlas Landfills,2019,,Rio de Janeiro,Rio de Janeiro,Brasil,True
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Waste Atlas Landfills,2019,,Goiânia,Goiás,Brasil,True
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Waste Atlas Landfills,2019,,Feira de Santana,Bahia,Brasil,True
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Waste Atlas Landfills,2019,,,Región Metropolitana de Santiago,Chile,False
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Waste Atlas Landfills,2019,,Zapopan,Jalisco,México,True
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Waste Atlas Landfills,2019,,,województwo warmińsko-mazurskie,Polska,False
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Waste Atlas Landfills,2019,Końskie,Końskie,województwo świętokrzyskie,Polska,False
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Waste Atlas Landfills,2019,,,województwo mazowieckie,Polska,False
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Waste Atlas Landfills,2019,,Chorzów,województwo śląskie,Polska,True
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Waste Atlas Landfills,2019,,,województwo dolnośląskie,Polska,False
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Waste Atlas Landfills,2019,,Општина Горњи Милановац,Централна Србија,Србија,True
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Waste Atlas Landfills,2019,,Jastrzębie-Zdrój,województwo śląskie,Polska,True
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Waste Atlas Landfills,2019,孤店子镇,新北街道,吉林省,中国,True
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Waste Atlas Landfills,2019,,,Московская область,Россия,False
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Waste Atlas Landfills,2019,,,Alba / Scotland,United Kingdom,False
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Waste Atlas Landfills,2019,,,Washington,United States,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,We need your support,Waste Atlas Landfills,2019,,Johnson City,Tennessee,United States,True
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,We need your support,Waste Atlas Landfills,2019,Loudon,Loudon,Tennessee,United States,False
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,We need your support,Waste Atlas Landfills,2019,Pigeon Forge,Pigeon Forge,Tennessee,United States,False
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States,False
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States,False
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,We need your support,Waste Atlas Landfills,2019,Menomonee Falls,Menomonee Falls,Wisconsin,United States,False
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States,True
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States,True
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States,False
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States,False
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,We need your support,Waste Atlas Landfills,2019,將軍澳 Tseung Kwan O,西貢區 Sai Kung District,香港 Hong Kong,中国,True
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,We need your support,Waste Atlas Landfills,2019,,元朗區 Yuen Long District,香港 Hong Kong,中国,True
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Waste Atlas Landfills,2019,,,Kweneng District,Botswana,False

In [84]:
# Create a new column 'availble city data' based on if the 'city' column is available or if it is missing. 
# If the value is FALSE, then that means the cities were generated through the java script code provided by Andre
df5_clean['Available City Data'] = df5_clean['City'].apply(lambda x: True if x else False)
df5_clean

,asset_id,latitude,longitude,category,Status,Area,waste,Annual capacity,population,Data Source,Year,town,City,state,country,Available City Data
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Waste Atlas Landfills,2019,,乌当区,贵州省,中国,True
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Waste Atlas Landfills,2019,,Caucaia,Ceará,Brasil,True
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Waste Atlas Landfills,2019,,São Paulo,São Paulo,Brasil,True
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Waste Atlas Landfills,2019,,Campinas,São Paulo,Brasil,True
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Waste Atlas Landfills,2019,,,Buenos Aires,Argentina,False
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Waste Atlas Landfills,2019,,Ciudad López Mateos,Estado de México,México,True
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Waste Atlas Landfills,2019,,Contagem,Minas Gerais,Brasil,True
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Waste Atlas Landfills,2019,,Valparaíso,Región de Valparaíso,Chile,True
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Waste Atlas Landfills,2019,,Perímetro Urbano Medellín,Antioquia,Colombia,True
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Waste Atlas Landfills,2019,,,,대한민국,False
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Waste Atlas Landfills,2019,,강릉시,,대한민국,True
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Waste Atlas Landfills,2019,,,Дніпропетровська область,Україна,False
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Waste Atlas Landfills,2019,,朝阳区,北京市,中国,True
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Waste Atlas Landfills,2019,,Gliwice,województwo śląskie,Polska,True
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Waste Atlas Landfills,2019,,Rio de Janeiro,Rio de Janeiro,Brasil,True
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Waste Atlas Landfills,2019,,Goiânia,Goiás,Brasil,True
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Waste Atlas Landfills,2019,,Feira de Santana,Bahia,Brasil,True
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Waste Atlas Landfills,2019,,,Región Metropolitana de Santiago,Chile,False
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Waste Atlas Landfills,2019,,Zapopan,Jalisco,México,True
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Waste Atlas Landfills,2019,,,województwo warmińsko-mazurskie,Polska,False
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Waste Atlas Landfills,2019,Końskie,Końskie,województwo świętokrzyskie,Polska,True
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Waste Atlas Landfills,2019,,,województwo mazowieckie,Polska,False
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Waste Atlas Landfills,2019,,Chorzów,województwo śląskie,Polska,True
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Waste Atlas Landfills,2019,,,województwo dolnośląskie,Polska,False
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Waste Atlas Landfills,2019,,Општина Горњи Милановац,Централна Србија,Србија,True
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Waste Atlas Landfills,2019,,Jastrzębie-Zdrój,województwo śląskie,Polska,True
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Waste Atlas Landfills,2019,孤店子镇,新北街道,吉林省,中国,True
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Waste Atlas Landfills,2019,,,Московская область,Россия,False
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Waste Atlas Landfills,2019,,,Alba / Scotland,United Kingdom,False
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Waste Atlas Landfills,2019,,,Washington,United States,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,We need your support,Waste Atlas Landfills,2019,,Johnson City,Tennessee,United States,True
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,We need your support,Waste Atlas Landfills,2019,Loudon,Loudon,Tennessee,United States,True
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,We need your support,Waste Atlas Landfills,2019,Pigeon Forge,Pigeon Forge,Tennessee,United States,True
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,We need your support,Waste Atlas Landfills,2019,,,Tennessee,United States,False
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States,False
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,We need your support,Waste Atlas Landfills,2019,,,United States Virgin Islands,United States,False
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,We need your support,Waste Atlas Landfills,2019,Menomonee Falls,Menomonee Falls,Wisconsin,United States,True
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States,True
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,We need your support,Waste Atlas Landfills,2019,,Clarksburg,West Virginia,United States,True
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States,False
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,We need your support,Waste Atlas Landfills,2019,,,West Virginia,United States,False
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,,,West Virginia,United States,False
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,We need your support,Waste Atlas Landfills,2019,將軍澳 Tseung Kwan O,西貢區 Sai Kung District,香港 Hong Kong,中国,True
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,We need your support,Waste Atlas Landfills,2019,,元朗區 Yuen Long District,香港 Hong Kong,中国,True
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Waste Atlas Landfills,2019,,,Kweneng District,Botswana,False

In [85]:
#creating an excel file because this code takes a long time to run
df5_clean.to_excel("df_waste_atlas_landfills.xlsx") 

df5_clean1 = pd.read_excel('df_waste_atlas_landfills.xlsx')

In [86]:
# There are some rows in the waste column that have a string "we need your support". remove them. 
# Define the string to remove
string_to_replace = 'We need your support'


df5_clean1 = df5_clean1.replace(string_to_replace, np.nan)


# Display the updated DataFrame
df5_clean1

,asset_id,latitude,longitude,category,Status,Area,waste,Annual capacity,population,Data Source,Year,town,City,state,country,Available City Data
0,GAOYAN,26.63574962,106.802924,Sanitary Landfills,Active,75.0,2320000.0,435450,4324561,Waste Atlas Landfills,2019,NaN,乌当区,贵州省,中国,True
1,ASMOC,-3.79650349,-38.669171,Sanitary Landfills,Active,78.0,24000000.0,1081848,3400000,Waste Atlas Landfills,2019,NaN,Caucaia,Ceará,Brasil,True
2,BANDEIRANTES,-23.42216056,-46.755441,Sanitary Landfills,Inactive,140.0,30000000.0,2000000,11316149,Waste Atlas Landfills,2019,NaN,São Paulo,São Paulo,Brasil,True
3,CAMPINAS,-22.91570936,-47.147012,Sanitary Landfills,Inactive,26.0,3900000.0,300000,1080999,Waste Atlas Landfills,2019,NaN,Campinas,São Paulo,Brasil,True
4,BAHIA BLANCA,-38.77201938,-62.155838,Sanitary Landfills,Active,48.0,1350000.0,78144,301572,Waste Atlas Landfills,2019,NaN,NaN,Buenos Aires,Argentina,False
5,PUERTO DE CHIVOS,19.5869222,-99.279070,Sanitary Landfills,Active,52.0,3300000.0,160600,8909,Waste Atlas Landfills,2019,NaN,Ciudad López Mateos,Estado de México,México,True
6,PEROBAS,-19.914218068,-44.058856,Sanitary Landfills,Active,12.0,1200000.0,198404,617741,Waste Atlas Landfills,2019,NaN,Contagem,Minas Gerais,Brasil,True
7,EL MOLLE,-33.08909661,-71.635022,Sanitary Landfills,Active,96.0,2394000.0,130000,275982,Waste Atlas Landfills,2019,NaN,Valparaíso,Región de Valparaíso,Chile,True
8,EL GUACAL,6.260436111,-75.631397,Sanitary Landfills,Active,27.0,1300000.0,190000,2743049,Waste Atlas Landfills,2019,NaN,Perímetro Urbano Medellín,Antioquia,Colombia,True
9,CHUNCHEON,37.797712686,127.678578,Sanitary Landfills,Active,13.0,1048190.0,69040,273130,Waste Atlas Landfills,2019,NaN,NaN,NaN,대한민국,False
10,GANGNEUNG,37.68945798,128.989449,Sanitary Landfills,Active,24.0,1376188.0,109000,229869,Waste Atlas Landfills,2019,NaN,강릉시,NaN,대한민국,True
11,DNEPROPETROVSK,48.65355184,35.181742,Sanitary Landfills,Inactive,29.0,740000.0,83900,1001612,Waste Atlas Landfills,2019,NaN,NaN,Дніпропетровська область,Україна,False
12,GAOANTUN,39.9440085,116.615119,Sanitary Landfills,Active,30.0,7000000.0,550000,3642000,Waste Atlas Landfills,2019,NaN,朝阳区,北京市,中国,True
13,GLIWICE,50.26333886,18.666973,Sanitary Landfills,Active,15.0,1200000.0,120000,2746000,Waste Atlas Landfills,2019,NaN,Gliwice,województwo śląskie,Polska,True
14,GERICINO,-22.84230502,-43.474917,Sanitary Landfills,Active,17.0,7700000.0,460000,244518,Waste Atlas Landfills,2019,NaN,Rio de Janeiro,Rio de Janeiro,Brasil,True
15,GOIANIA,-16.64532007,-49.365993,Sanitary Landfills,Active,26.0,7100000.0,460000,1301892,Waste Atlas Landfills,2019,NaN,Goiânia,Goiás,Brasil,True
16,FEIRA DE SANTANA,-12.24439804,-38.990865,Sanitary Landfills,Active,10.0,500000.0,130000,740000,Waste Atlas Landfills,2019,NaN,Feira de Santana,Bahia,Brasil,True
17,LEPANTO DEPOSIT I,-33.62937825,-70.668912,Sanitary Landfills,Inactive,18.0,7371100.0,We need your suppo,246762,Waste Atlas Landfills,2019,NaN,NaN,Región Metropolitana de Santiago,Chile,False
18,HASARS,20.91887362,-103.454432,Sanitary Landfills,Active,10.0,4600000.0,450000,1155790,Waste Atlas Landfills,2019,NaN,Zapopan,Jalisco,México,True
19,LEGAJNY,53.81717293,20.625844,Sanitary Landfills,Inactive,12.0,1600000.0,1600000,113529,Waste Atlas Landfills,2019,NaN,NaN,województwo warmińsko-mazurskie,Polska,False
20,KONSKIE,51.18041908,20.376549,Sanitary Landfills,Active,5.0,396880.0,11000,20328,Waste Atlas Landfills,2019,Końskie,Końskie,województwo świętokrzyskie,Polska,True
21,KOBIERNIKI,52.61391484,19.593730,Sanitary Landfills,Active,2.0,240000.0,18000,126675,Waste Atlas Landfills,2019,NaN,NaN,województwo mazowieckie,Polska,False
22,KATOWISE,50.32679268,18.983334,Sanitary Landfills,Active,5.0,320.0,45000,308724,Waste Atlas Landfills,2019,NaN,Chorzów,województwo śląskie,Polska,True
23,GAC OLAWA,50.888145302,17.390842,Sanitary Landfills,Active,3.0,370000.0,65000,38303,Waste Atlas Landfills,2019,NaN,NaN,województwo dolnośląskie,Polska,False
24,GORNJI MILANOVAC,43.98985047,20.426309,Sanitary Landfills,Active,2.0,199148.0,16500,44438,Waste Atlas Landfills,2019,NaN,Општина Горњи Милановац,Централна Србија,Србија,True
25,JASTRZEBIE,49.96866843,18.644400,Sanitary Landfills,Active,10.0,500000.0,70000,92462,Waste Atlas Landfills,2019,NaN,Jastrzębie-Zdrój,województwo śląskie,Polska,True
26,JILIN CITY LANDFILL,43.90101561,126.452765,Sanitary Landfills,Active,30.0,2500000.0,300000,1975803,Waste Atlas Landfills,2019,孤店子镇,新北街道,吉林省,中国,True
27,KARGASHINO,55.9622764,37.758514,Sanitary Landfills,Active,12.0,1320000.0,100000,11503501,Waste Atlas Landfills,2019,NaN,NaN,Московская область,Россия,False
28,GREENGAIRS,55.90277106,-3.932633,Sanitary Landfills,Active,40.0,20500000.0,300000,326400,Waste Atlas Landfills,2019,NaN,NaN,Alba / Scotland,United Kingdom,False
29,ROOSEVELT REGIONAL LANDFILL,45.80911919,-120.179958,Sanitary Landfills,Active,1030.0,54000000.0,3029500,6830038,Waste Atlas Landfills,2019,NaN,NaN,Washington,United States,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,DICKSON COUNTY LANDFILL,36.0664777471676,-87.428373,Sanitary Landfills,Inactive,30.0,724581.0,22880,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
540,WEST CAMDEN SANITARY LANDFILL,36.0527015447095,-88.141155,Sanitary Landfills,Active,65.6,8727773.0,355730,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
541,IRIS GLEN LANDFILL,36.3293967675205,-82.332747,Sanitary Landfills,Active,27.5,3500000.0,325000,NaN,Waste Atlas Landfills,2019,NaN,Johnson City,Tennessee,United States,True
542,LOUDON COUNTY SANITARY LANDFILL,35.7484147899653,-84.411361,Sanitary Landfills,Active,27.1,900000.0,43200,NaN,Waste Atlas Landfills,2019,Loudon,Loudon,Tennessee,United States,True
543,McMINN COUNTY LANDFILL,35.3875456740406,-84.585606,Sanitary Landfills,Active,53.8,231996.0,43758,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
544,McNAIRY COUNTY LANDFILL,35.2145609949034,-88.517979,Sanitary Landfills,Inactive,35.6,700637.0,54912,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
545,MIDDLE POINT LANDFILL,35.9374381784581,-86.366873,Sanitary Landfills,Active,838.0,12556163.0,1092000,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
546,PICKETT COUNTY LANDFILL,36.5625286249178,-85.119014,Sanitary Landfills,Active,21.0,60435.0,3432,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
547,RHEA COUNTY LANDFILL,35.5604602647575,-84.911697,Sanitary Landfills,Active,139.6,616688.0,24310,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
548,"SEVIER SOLID WASTE, INCORPORATED",35.8183157758771,-83.549998,Sanitary Landfills,Active,4.1,253402.0,17160,NaN,Waste Atlas Landfills,2019,Pigeon Forge,Pigeon Forge,Tennessee,United States,True
549,CARTER VALLEY LANDFILL,36.5454628460655,-82.786921,Sanitary Landfills,Active,46.5,12723765.0,312000,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
550,CITY OF CHATTANOOGA LANDFILL,35.2013093724484,-85.073989,Sanitary Landfills,Active,12.1,1500000.0,80000,NaN,Waste Atlas Landfills,2019,NaN,NaN,Tennessee,United States,False
551,ANGUILLA LANDFILL,17.6984386054228,-64.781700,Sanitary Landfills,Inactive,14.2,2200000.0,100000,NaN,Waste Atlas Landfills,2019,NaN,NaN,United States Virgin Islands,United States,False
552,BOVONI LANDFILL,18.3115043362071,-64.884889,Sanitary Landfills,Inactive,13.8,1500000.0,85000,NaN,Waste Atlas Landfills,2019,NaN,NaN,United States Virgin Islands,United States,False
553,ORCHARD RIDGE RDF,43.181576729089,-88.075781,Sanitary Landfills,Active,60.7,28174968.0,687500,NaN,Waste Atlas Landfills,2019,Menomonee Falls,Menomonee Falls,Wisconsin,United States,True
554,RALEIGH COUNTY SWA,37.8272113992,-81.165067,Sanitary Landfills,Active,9.3,1600000.0,128484,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
555,MEADOWFILL LANDFILL,39.3366421712798,-80.257507,Sanitary Landfills,Active,71.9,2250000.0,269544,NaN,Waste Atlas Landfills,2019,NaN,Clarksburg,West Virginia,United States,True
556,LCS SERVICES LANDFILL,39.5714297754422,-77.990697,Sanitary Landfills,Active,27.1,1934347.0,130308,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
557,S AND S GRADING Inc. LANDFILL,39.2211423765028,-80.408328,Sanitary Landfills,Active,26.7,660000.0,70740,NaN,Waste Atlas Landfills,2019,NaN,Clarksburg,West Virginia,United States,True
558,NORTHWESTERN COMPANY DISPOSAL LANDFILL,39.2502841712002,-81.493484,Sanitary Landfills,Active,23.5,4100000.0,228732,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
559,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,39.14394831844,-79.470436,Sanitary Landfills,Inactive,24.2,2076056.0,76056,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
560,MERCER COUNTY LANDFILL,37.3283973570991,-81.125851,Sanitary Landfills,Active,16.2,1400000.0,47100,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
561,GREENBRIER COUNTY LANDFILL,37.8195709969124,-80.381584,Sanitary Landfills,Active,72.8,780000.0,44460,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
562,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,38.3316365788095,-80.694782,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
563,SHORT CREEK SANITARY LANDFILL,40.1480251528179,-80.640414,Sanitary Landfills,Active,46.5,2985349.0,216540,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
564,WETZEL COUNTY LANDFILL,39.6044400316229,-80.862568,Sanitary Landfills,Active,56.3,1000000.0,60000,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
565,BROOKE COUNTY LANDFILL (SUBTITLE D),40.379005745313,-80.577606,Sanitary Landfills,NaN,NaN,NaN,NaN,NaN,Waste Atlas Landfills,2019,NaN,NaN,West Virginia,United States,False
566,SOUTH EAST NEW TERRITORIES LANDFILL,22.2820827,114.280131,Sanitary Landfills,Active,100.0,33288000.0,1752000,NaN,Waste Atlas Landfills,2019,將軍澳 Tseung Kwan O,西貢區 Sai Kung District,香港 Hong Kong,中国,True
567,WEST NEW TERRITORIES LANDFILL,22.4214327,113.934456,Sanitary Landfills,Active,110.0,46720000.0,2336000,NaN,Waste Atlas Landfills,2019,NaN,元朗區 Yuen Long District,香港 Hong Kong,中国,True
568,GAMODUBU LANDFILL,-24.48614571803265,25.714106,Sanitary Landfills,Active,30.0,316000.0,79000,427232,Waste Atlas Landfills,2019,NaN,NaN,Kweneng District,Botswana,False

In [88]:
#We are missing much city data, however Andre was able to give javascript code to fix it, let's count how many need fixed
value_counts = df5_clean1['Available City Data'].value_counts()

# Get the count of "True" and "False"
count_true = value_counts[True]
count_false = value_counts[False]

# Print the counts
print("Count of True:", count_true)
print("Count of False:", count_false)

# True:264
# False: 305

Count of True: 264
Count of False: 305

In [ ]:
# This code was used in google sheets to find cities for the 305 values
'''

function cityOf(geocode) {

  geolat=geocode.split(",")[0]
  geolng=geocode.split(",")[1]

  var city = Maps.newGeocoder().reverseGeocode(geolat,geolng)["results"][0]["address_components"][1]["long_name"];
  var state = Maps.newGeocoder().reverseGeocode(geolat,geolng)["results"][0]["address_components"][3]["short_name"];
  response=city

  return response

  
}


'''

In [91]:
df5_clean1.to_excel("df_waste_atlas_landfills_final.xlsx")

In [101]:
# Merging df2,df4,and df5 together to create waste dataset
df_waste = pd.concat([df2_clean, df4_clean1, df5_clean1], ignore_index=False, axis=0)
df_waste.to_excel("waste1.xlsx") 
df_waste

#total of 991 rows x 42 columns

# so 649 rows of asset level waste data
# 329 rows of city level waste data -- hopefully 978 rows of city level

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,asset_id,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,NaN,NaN,True,Hirat√Ç¬†,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,NaN,NaN,True,C√É¬≥rdoba,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,NaN,NaN,True,Ciudada Aut√É¬≥noma De Buenos Aires (Caba).,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,NaN,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,22880,30.0,False,NaN,Waste Atlas Landfills,NaN,NaN,Inactive,2019,DICKSON COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,355730,65.6,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,WEST CAMDEN SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,325000,27.5,True,Johnson City,Waste Atlas Landfills,NaN,NaN,Active,2019,IRIS GLEN LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,43200,27.1,True,Loudon,Waste Atlas Landfills,NaN,NaN,Active,2019,LOUDON COUNTY SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,43758,53.8,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,McMINN COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,54912,35.6,False,NaN,Waste Atlas Landfills,NaN,NaN,Inactive,2019,McNAIRY COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
545,1092000,838.0,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,MIDDLE POINT LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,3432,21.0,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,PICKETT COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,24310,139.6,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,RHEA COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,17160,4.1,True,Pigeon Forge,Waste Atlas Landfills,NaN,NaN,Active,2019,"SEVIER SOLID WASTE, INCORPORATED",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,312000,46.5,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,CARTER VALLEY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
550,80000,12.1,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,CITY OF CHATTANOOGA LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
551,100000,14.2,False,NaN,Waste Atlas Landfills,NaN,NaN,Inactive,2019,ANGUILLA LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552,85000,13.8,False,NaN,Waste Atlas Landfills,NaN,NaN,Inactive,2019,BOVONI LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,687500,60.7,True,Menomonee Falls,Waste Atlas Landfills,NaN,NaN,Active,2019,ORCHARD RIDGE RDF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,128484,9.3,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,RALEIGH COUNTY SWA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,269544,71.9,True,Clarksburg,Waste Atlas Landfills,NaN,NaN,Active,2019,MEADOWFILL LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,130308,27.1,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,LCS SERVICES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,70740,26.7,True,Clarksburg,Waste Atlas Landfills,NaN,NaN,Active,2019,S AND S GRADING Inc. LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,228732,23.5,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,NORTHWESTERN COMPANY DISPOSAL LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,76056,24.2,False,NaN,Waste Atlas Landfills,NaN,NaN,Inactive,2019,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,47100,16.2,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,MERCER COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,44460,72.8,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,GREENBRIER COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,NaN,NaN,False,NaN,Waste Atlas Landfills,NaN,NaN,NaN,2019,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
563,216540,46.5,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,SHORT CREEK SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,60000,56.3,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,WETZEL COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
565,NaN,NaN,False,NaN,Waste Atlas Landfills,NaN,NaN,NaN,2019,BROOKE COUNTY LANDFILL (SUBTITLE D),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,1752000,100.0,True,西貢區 Sai Kung District,Waste Atlas Landfills,NaN,NaN,Active,2019,SOUTH EAST NEW TERRITORIES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,2336000,110.0,True,元朗區 Yuen Long District,Waste Atlas Landfills,NaN,NaN,Active,2019,WEST NEW TERRITORIES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,79000,30.0,False,NaN,Waste Atlas Landfills,NaN,NaN,Active,2019,GAMODUBU LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#My code filled an additional 325 cities, and andre's code filled the remaining 324 cities so now all 978 rows have complete city data

In [ ]:
# At this point I ran Andre's code through google sheets and manually entered it into a dataset titled 'wastefinal'

In [16]:
df_waste_final = pd.read_excel('wastefinal.xlsx')
df_waste_final

#991 rows x 42 columns
# Complete city column

,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,asset_id,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,NaN,NaN,True,Ciudada Aut√É¬≥noma De Buenos Aires (Caba).,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,NaN,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,22880,30.0,False,Eno Road,Waste Atlas Landfills,NaN,NaN,Inactive,2019,DICKSON COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,355730,65.6,False,Camden,Waste Atlas Landfills,NaN,NaN,Active,2019,WEST CAMDEN SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,325000,27.5,True,Johnson City,Waste Atlas Landfills,NaN,NaN,Active,2019,IRIS GLEN LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,43200,27.1,True,Loudon,Waste Atlas Landfills,NaN,NaN,Active,2019,LOUDON COUNTY SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,43758,53.8,False,Athens,Waste Atlas Landfills,NaN,NaN,Active,2019,McMINN COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,54912,35.6,False,Purdy,Waste Atlas Landfills,NaN,NaN,Inactive,2019,McNAIRY COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
545,1092000,838.0,False,Walterhill,Waste Atlas Landfills,NaN,NaN,Active,2019,MIDDLE POINT LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,3432,21.0,False,Gib Moles Road,Waste Atlas Landfills,NaN,NaN,Active,2019,PICKETT COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,24310,139.6,False,Evensville,Waste Atlas Landfills,NaN,NaN,Active,2019,RHEA COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,17160,4.1,True,Parlin Drive,Waste Atlas Landfills,NaN,NaN,Active,2019,"SEVIER SOLID WASTE, INCORPORATED",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,312000,46.5,False,Church Hill,Waste Atlas Landfills,NaN,NaN,Active,2019,CARTER VALLEY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
550,80000,12.1,False,Ooltewah,Waste Atlas Landfills,NaN,NaN,Active,2019,CITY OF CHATTANOOGA LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
551,100000,14.2,False,Frederiksted Southeast,Waste Atlas Landfills,NaN,NaN,Inactive,2019,ANGUILLA LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552,85000,13.8,False,Estate Bovoni,Waste Atlas Landfills,NaN,NaN,Inactive,2019,BOVONI LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,687500,60.7,True,Menomonee Falls,Waste Atlas Landfills,NaN,NaN,Active,2019,ORCHARD RIDGE RDF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,128484,9.3,False,Piney View,Waste Atlas Landfills,NaN,NaN,Active,2019,RALEIGH COUNTY SWA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,269544,71.9,True,Clarksburg,Waste Atlas Landfills,NaN,NaN,Active,2019,MEADOWFILL LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,130308,27.1,False,Hedgesville,Waste Atlas Landfills,NaN,NaN,Active,2019,LCS SERVICES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,70740,26.7,True,Milford Street,Waste Atlas Landfills,NaN,NaN,Active,2019,S AND S GRADING Inc. LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,228732,23.5,False,Parkersburg,Waste Atlas Landfills,NaN,NaN,Active,2019,NORTHWESTERN COMPANY DISPOSAL LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,76056,24.2,False,Davis,Waste Atlas Landfills,NaN,NaN,Inactive,2019,TUCKER COUNTY SOLID WASTE AUTHORITY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,47100,16.2,False,Maple Acres,Waste Atlas Landfills,NaN,NaN,Active,2019,MERCER COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,44460,72.8,False,Hopper,Waste Atlas Landfills,NaN,NaN,Active,2019,GREENBRIER COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,NaN,NaN,False,Craigsville,Waste Atlas Landfills,NaN,NaN,NaN,2019,NICHOLAS COUNTY SOLID WASTE AUTHORITY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
563,216540,46.5,False,Betty Zane,Waste Atlas Landfills,NaN,NaN,Active,2019,SHORT CREEK SANITARY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,60000,56.3,False,New Martinsville,Waste Atlas Landfills,NaN,NaN,Active,2019,WETZEL COUNTY LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
565,NaN,NaN,False,Weirton,Waste Atlas Landfills,NaN,NaN,NaN,2019,BROOKE COUNTY LANDFILL (SUBTITLE D),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,1752000,100.0,True,Clear Water Bay,Waste Atlas Landfills,NaN,NaN,Active,2019,SOUTH EAST NEW TERRITORIES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,2336000,110.0,True,Tuen Mun,Waste Atlas Landfills,NaN,NaN,Active,2019,WEST NEW TERRITORIES LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,79000,30.0,False,Gamodubu,Waste Atlas Landfills,NaN,NaN,Active,2019,GAMODUBU LANDFILL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#df6 cleaning

In [14]:
# lets get rid of rows that have NA values for the waste column
# need to multiply generated MSW by 365 so that it is tons per year

#before dropping NAs there were 47 rows × 15 columns
df6.dropna(subset = ['waste'], inplace=True)
df6.dropna(subset = ['City'], inplace=True)



df6['waste'] = df6['waste']*365
df6['Data Source'] = 'MSW Asia Pacific'

df6_clean = df6


# Create a new column 'availble city data' based on if the 'city' column is available or if it is missing. 
# If the value is FALSE, then that means the cities were generated through the java script code provided by Andre
df6_clean['Available City Data'] = df6_clean['City'].notna()


df6_clean.rename(columns={'population ':'population', 'country ':'country'
                   }, inplace=True)


df6_clean

#48 rows x 17 columns

,country,City,state,waste,population,Year,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,Data Source,Available City Data
0,India,Baidyabati,NaN,22995.00,121110,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
1,India,Bangalore,NaN,1642500.00,9590000,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
2,Nepal,Bhaktapur,NaN,10950.00,83893,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
3,Mongolia,Bulgan,NaN,2664.50,12486,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
5,India,Champdani,NaN,14600.00,111251,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
6,Bangladesh,Chittagong,NaN,584000.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
8,Sri Lanka,Dehiwala Mount Lavinia,NaN,63948.00,185235,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
9,Bangladesh,Dhaka,NaN,766500.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
10,Bangladesh,Dhaka,NaN,1095000.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
11,Bangladesh,Dhaka,NaN,1495770.00,12000000,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
14,Pakistan,Gujranwala,NaN,438000.00,2050000,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
15,Viet Nam,Ho Chi Minh,NaN,2628000.00,7818200,2015,83.1,0.4,0.1,NaN,2.0,0.1,0.1,0.2,1.3,MSW Asia Pacific,True
16,Sri Lanka,Jaffna,NaN,38277.55,90559,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
20,Nepal,Kathmandu,NaN,173375.00,1006656,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
21,Sri Lanka,Katunayake Seeduwa,NaN,21024.00,63243,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
22,Sri Lanka,Kesbewa,NaN,33507.00,191334,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
24,Nepal,Kirtipur,NaN,7300.00,66070,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
25,India,Kolkata,NaN,127750.00,774049,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
26,India,Konnagar,NaN,12410.00,76122,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
27,Sri Lanka,Kurunegala,NaN,19618.75,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
28,Sri Lanka,Kurunegala,NaN,17545.55,26903,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
30,Nepal,Lalitpur,NaN,36500.00,223285,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
31,Fiji,Lautoka market,NaN,693.50,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
32,Sri Lanka,Moratuwa Municipal,NaN,45442.50,169630,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
33,Sri Lanka,Nuwara Eliya,NaN,11680.00,24709,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
34,Indonesia,Palembang,NaN,364270.00,1589780,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
36,Sri Lanka,Ratnapura,NaN,19622.40,54373,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
37,India,Rishra,NaN,19345.00,124577,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
38,India,Serampore,NaN,32850.00,181842,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
40,Nepal,Thimi,NaN,9490.00,84259,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
41,Sri Lanka,Trincomalee,NaN,22662.85,55564,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
47,India,Uttarpara-Kotrung,NaN,25550.00,159147,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True

In [32]:
df6_clean.rename(columns={'country ':'country'
                   }, inplace=True)
df6_clean

,country,City,state,waste,population,Year,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,Data Source,Available City Data
0,India,Baidyabati,NaN,22995.00,121110,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
1,India,Bangalore,NaN,1642500.00,9590000,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
2,Nepal,Bhaktapur,NaN,10950.00,83893,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
3,Mongolia,Bulgan,NaN,2664.50,12486,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
5,India,Champdani,NaN,14600.00,111251,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
6,Bangladesh,Chittagong,NaN,584000.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
8,Sri Lanka,Dehiwala Mount Lavinia,NaN,63948.00,185235,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
9,Bangladesh,Dhaka,NaN,766500.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
10,Bangladesh,Dhaka,NaN,1095000.00,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
11,Bangladesh,Dhaka,NaN,1495770.00,12000000,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
14,Pakistan,Gujranwala,NaN,438000.00,2050000,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
15,Viet Nam,Ho Chi Minh,NaN,2628000.00,7818200,2015,83.1,0.4,0.1,NaN,2.0,0.1,0.1,0.2,1.3,MSW Asia Pacific,True
16,Sri Lanka,Jaffna,NaN,38277.55,90559,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
20,Nepal,Kathmandu,NaN,173375.00,1006656,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
21,Sri Lanka,Katunayake Seeduwa,NaN,21024.00,63243,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
22,Sri Lanka,Kesbewa,NaN,33507.00,191334,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
24,Nepal,Kirtipur,NaN,7300.00,66070,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
25,India,Kolkata,NaN,127750.00,774049,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
26,India,Konnagar,NaN,12410.00,76122,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
27,Sri Lanka,Kurunegala,NaN,19618.75,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
28,Sri Lanka,Kurunegala,NaN,17545.55,26903,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
30,Nepal,Lalitpur,NaN,36500.00,223285,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
31,Fiji,Lautoka market,NaN,693.50,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
32,Sri Lanka,Moratuwa Municipal,NaN,45442.50,169630,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
33,Sri Lanka,Nuwara Eliya,NaN,11680.00,24709,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
34,Indonesia,Palembang,NaN,364270.00,1589780,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
36,Sri Lanka,Ratnapura,NaN,19622.40,54373,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
37,India,Rishra,NaN,19345.00,124577,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
38,India,Serampore,NaN,32850.00,181842,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
40,Nepal,Thimi,NaN,9490.00,84259,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
41,Sri Lanka,Trincomalee,NaN,22662.85,55564,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True
47,India,Uttarpara-Kotrung,NaN,25550.00,159147,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MSW Asia Pacific,True

In [33]:
# Merging df6 and final waste
df_waste_final2 = pd.concat([df_waste_final, df6_clean], ignore_index=False, axis=0)
df_waste_final2.to_excel("wastefinal2.xlsx") 
df_waste_final2


#total of 1023 rows x 44 columns

/Users/rowansharkey/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,asset_id,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,NaN,NaN,True,Ciudada Aut√É¬≥noma De Buenos Aires (Caba).,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,NaN,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,NaN,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,True,Jaffna,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Found a few strange symbols such as √Ç¬†  in a few columns, so I manually removed them and googled the city name
# made a new data set and will now load it in
df_waste_final3 = pd.read_excel('wastefinal3.xlsx')

In [136]:
value_counts = df_waste_final3['City'].value_counts()

# Print the value counts
print(value_counts)

Levant                    4
San Jose                  3
Amman                     3
Salta                     3
Bakersfield               3
Dhaka                     3
Ibadan                    3
Los Angeles               3
Yangon                    3
Ann Arbor                 2
Phnom Penh                2
Lusaka                    2
Bhaktapur                 2
Glendale                  2
North Arlington           2
Managua                   2
Bengaluru                 2
Campo de Mayo             2
Kurunegala                2
Vinča                     2
Durban                    2
Maputo                    2
Crimean Peninsula         2
Chennai                   2
San Diego                 2
Lahore                    2
San Miguel                2
Athens                    2
Tullytown                 2
Aurora                    2
                         ..
Sao Paulo                 1
Waggaman                  1
Mpizani                   1
Hanford                   1
Laidzes pagasts           1
Jaipur                    1
Ottawa                    1
Jalalabad                 1
Tajiguas Landfill Road    1
Fuahmulah                 1
Lewisville                1
Mombasa                   1
North Porter Road         1
Kathmandu                 1
Lansing                   1
Val Verde                 1
Nashik                    1
Azusa                     1
Baghdad                   1
Sedouikech                1
Citrolândia               1
Nagpur                    1
Vijaywada                 1
Bački Petrovac            1
Corona                    1
Osaka                     1
McElhattan                1
Hosha                     1
Djiibouti City            1
Canberra                  1
Name: City, Length: 963, dtype: int64

In [26]:
# Check for duplicates based on the three columns
df_waste_final3['duplicate_rows'] = df_waste_final3.duplicated(subset=['asset_id', 'Year', 'City'], keep=False)

df_waste_final3

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,duplicate_rows
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00,False
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN,False
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN,False
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN,False
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN,False
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN,False
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88,False
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00,False
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84,False
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00,False
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22,False
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN,False
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN,False
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00,False
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
999,1000,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1000,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1001,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1002,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1003,1004,NaN,NaN,True,Jaffna,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1004,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1005,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1006,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1007,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1008,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1009,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1010,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1011,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1012,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1013,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1014,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1015,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1016,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1017,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1018,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1019,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1020,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1021,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1022,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [138]:
value_counts = df_waste_final3['duplicate_rows'].value_counts()

# Print the value counts
print(value_counts)

# one pair of duplicates is from MSW_AsiaPacific data set and can be found in wastefinal3 in rows 1000 and 999
# The second pair can be found in rows 189 (world bank) and 1004 (MSW). I would recommend keeping the world bank value bc it has data about composition

False    1019
True        4
Name: duplicate_rows, dtype: int64

In [3]:
test = df_waste_final3
test.set_index('Index')

test

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1000,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1004,NaN,NaN,True,Jaffna,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
test = df_waste_final3

# Specify the indices of the duplicate rows to be combined

index1 = 998
index2 = 999


# Calculate the average of 'waste' for the two rows
avg_waste1 = (test.loc[index1, 'waste'] + test.loc[index2, 'waste']) / 2






# Update the first row with the averaged value
test.at[index1, 'waste'] = avg_waste1



# Drop the second row
test.drop(index2, inplace=True)



# Reset the index if needed
test.reset_index(drop=True, inplace=True)

# Print the updated DataFrame
test






#test.at[1000,'waste']='Safa'

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1004,NaN,NaN,True,Jaffna,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Specify the indices of the duplicate rows to be combined
index1 = 187
index2 = 1002


# waste value for row 1004 is 38277.55 and for row 189 it is 38278
# since they are the same, we can just drop row 1004


# Calculate the average of 'waste' for the two rows
avg_waste1 = (38278 + 38277.55) / 2




# Update the first row with the averaged value
test.at[index1, 'waste'] = avg_waste1



# Drop the second row
test.drop(index2, inplace=True)



# Reset the index if needed
test.reset_index(drop=True, inplace=True)

# Print the updated DataFrame
test

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,NaN,NaN,True,Baidyabati,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
wastefinal4 = test

wastefinal4

# 1021 rows × 42 columns

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,NaN,NaN,True,Baidyabati,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# There are some rows in the waste column that have a string "we need your support". remove them. 
# Define the string to remove
string_to_replace = 'We need your suppor'
wastefinal4 = wastefinal4.replace(string_to_replace, np.nan)

#wastefinal4['waste'] = wastefinal4['waste'].str.replace('', 'NaN')

# Remove rows containing the string "NaN"
wastefinal4 = wastefinal4[wastefinal4['waste'] != 'nan']
#wastefinal4 = wastefinal4[wastefinal4['waste'].dropna()
wastefinal4 = wastefinal4.dropna(subset=['waste'])



# Now there are 1001 rows × 44 columns --> so we lost 20 datapoints
wastefinal4

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,NaN,NaN,True,Baidyabati,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#The waste column has two values in some rows, I need to split those up and average them. 

wastefinal4['waste'] = wastefinal4['waste'].astype(str)
wastefinal4['waste'] = wastefinal4['waste'].str.replace('-', ',')

In [9]:

# Calculate the average

wastefinal4[['value1', 'value2']] = wastefinal4['waste'].str.split(',', expand=True)
wastefinal4['value2'] = wastefinal4['value2'].fillna(wastefinal4['value1'])

# now we have two columns, but the 'value2' column has a few NAs which need to be filled


wastefinal4['value1'] = wastefinal4['value1'].astype(float)
wastefinal4['value2'] = wastefinal4['value2'].astype(float)

# now we can average them
wastefinal4['waste'] = (wastefinal4['value1'] + wastefinal4['value2']) / 2

wastefinal4 = wastefinal4.drop(columns=['value1', 'value2'])


wastefinal4

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,NaN,NaN,True,Baidyabati,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1003,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1016,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1017,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#This code works to identify some countries but not all so gonna do it manually

'''

!pip install langdetect
!pip install translate
from langdetect import detect
from translate import Translator
import pandas as pd

# Assuming you have a DataFrame named 'df' with a column named 'country'

# Function to translate a single value to English
def translate_to_english(value):
    try:
        # Detect the language of the value
        lang = detect(value)

        # Translate the value to English
        translator = Translator(from_lang=lang, to_lang='en')
        translation = translator.translate(value)

        return translation
    except:
        return value

# Apply the translation function to the 'country' column
wastefinal4['country'] = wastefinal4['country'].apply(translate_to_english)

'''

"\n\n!pip install langdetect\n!pip install translate\nfrom langdetect import detect\nfrom translate import Translator\nimport pandas as pd\n\n# Assuming you have a DataFrame named 'df' with a column named 'country'\n\n# Function to translate a single value to English\ndef translate_to_english(value):\n    try:\n        # Detect the language of the value\n        lang = detect(value)\n\n        # Translate the value to English\n        translator = Translator(from_lang=lang, to_lang='en')\n        translation = translator.translate(value)\n\n        return translation\n    except:\n        return value\n\n# Apply the translation function to the 'country' column\nwastefinal4['country'] = wastefinal4['country'].apply(translate_to_english)\n\n"

In [11]:
replace_map = {
   'Egypt, Arab Rep.': 'Egypt',
'Iran, Islamic Rep.': 'Iran',
'Kosova / Kosovo': 'Kosovo',
'România': 'Romania',
'Ayiti': 'Haiti',
'ព្រះរាជាណាចក្រ​កម្ពុជា': 'Cambodia',
'Ελλάς': 'Greece',
'Maroc / ⵍⵎⵖⵔⵉⴱ / المغرب': 'Morocco',
'Україна': 'Ukraine',
'Россия': 'Russia',
'България': 'Bulgaris',
'Հայաստան': 'Armenia',
'Србија': 'Serbia',
'Кыргызстан': 'Kyrgyzstan',
'Türkiye': 'Turkey',
'تونس': 'Tunisia',
'مصر': 'Egypt',
'ኢትዮጵያ': 'Ethiopia',
'Djibouti جيبوتي': 'Djibouti',
'မြန်မာ': 'Myanmar',
'中国': 'China',
'대한민국': 'South Korea',
'ایران': 'Iran',
'پاکستان': 'Pakistan',
'الأردن': 'Jordan',
'لبنان': 'Lebanon',
'Macedonia, FYR': 'Macedonia',
'Russian Federation':'Russia',
'Venezuela, RB': 'Venezuela',
'Yemen, Rep.': 'Yemen',
'Sénégal': 'Senegal',
"Timór Lorosa'e / Timor-Leste": 'Timor-Leste',
'Polska': 'Poland',
'Қазақстан': 'Kazakhstan',
'Brasil': 'Brazil',
'République démocratique du Congo':'Democratic Republic of the Congo',
'Mauritius / Maurice': 'Mauritius',
'New Zealand/Aotearoa': 'New Zealand',
'Viet Nam': 'Vietnam',
'Micronesia, Fed. Sts.': 'Micronesia',
'Gambia, The': 'Gambia',
'Korea, Rep.':'South Korea',
'Lao PDR': 'Laos',
'Kyrgyz Republic': 'Kyrgyzstan',
'Slovak Republic': 'Slovakia',
'Bulgaris': 'Bulgaria'
    
    
}





# Replace the strings in the 'column_name' column
wastefinal4['country'] = wastefinal4['country'].replace(replace_map)

In [12]:
# the city finder code identified a lot of specific streets and highways instead of the city. Manually fixed
replace_city = {
'Ogunrinde Street': 'Lagos',
'Ikotun': 'Lagos',
'Nosakhare Bernard Street': 'Lagos',
'Hansen Road': 'Accra,',
'Fowosed': 'Lagos',
'Railroad Street': 'Lewisville',
'Avalon Street': 'Lompoc',
'White Street': 'Greensboro',
'Milford Street': 'West Milford',
'Road': 'Rumuoqonoma',
'Xindong Road': 'Guiyang',
'Landfill Road': 'Pinetown',
'Cemetary Road': 'Angleton',
'Coffin Butte Road': 'Adair Village,',
'Noth Porter Road': 'Joseph City',
'South Tomahawk Road': 'Apache Junction',
'East Irvington Road': 'Tucson',
'East Valeska Road': 'Tucson',
'West Tangerine Road': 'Marana',
'Bronco Trail Road Northeast': 'Rio Rancho',
'Silver Queen Road': 'Mojave',
'Bowman Road': 'China Lake Acres',
'Railroad Street': 'Lewisville',
'Dillard Access Road': 'Pleasant Hill',
'North Dump Road': 'Sage Creek Junction',
'Mount Pisgah Road': 'Yorkana',
'Fruitridge Road': 'Sacramento',
'Twin Oaks Valley Road':'Bonsall',
'Maxwell Road': 'Chula Vista',
'Pamo Road': 'Ramona',
'Tajiguas Landfill Road': 'Solvang',
"Guadalupe Mines Road": 'San Jose',
'San Andreas Road': 'Watsonville',
'West Hatch Road': 'Riverdale Park',
'East Washburn Road': 'Waterloo',
'Wiley Road':'Wichita Falls',
'Phillips County Road 217 Road': 'West Helena',
'Old Belchertown Road': 'Amherst',
'Glendale Road': 'Northampton',
'Anderson Ridge Road': 'Five Forks',
'Highway Church Road': 'Columbia',
'Panther Branch Road':'Alexander',
'Cheraw Road': 'Abingdon',
'Old Smithfield Road': 'Holly Springs',
"Southwest Greenville Hill's Road": 'Greenville',
'Brown Road': 'Auburn Hills',
'Angling Road': 'Coloma Charter Township',
'East Wheeler Road': 'Midland',
'Eno Road': 'Dickson',
'Gib Moles Road': 'Byrdstown',
'Highway 71 Northeast':'New London',
'Northeast University Avenue': 'Mitchellville',
'Ocean Heights Avenue': 'Egg Harbor Township',
'Freidriechstadt Avenue': 'Woodbine',
"Mount Pisgah Avenue": 'White',
'Clyde Park Avenue Southwest': 'Byron Center',
'East Mesquite Avenue': 'Pahrump',
'South 99th Avenue': 'Mobile',
'Boron Avenue':'Boron',
'Davis Avenue': 'Clearlake',
'66th Avenue': 'Mecca',
'84th Avenue': 'Oasis',
'Ghazipur Dairy Farm': 'Dehli',
'Mar del Plata': 'Buenos Aires',
'Bahía Blanca':'Buenos Aires',
'Don Torcuato': 'Buenos Aires',
'Campo de Mayo': 'Buenos Aires',
"Ensenada": 'Buenos Aires',
'Pergamino': 'Buenos Aires',
'San Nicolás de los Arroyos': 'Buenos Aires',
'González Catán': 'Buenos Aires',
'Güemes': 'Buenos Aires',
'Ex-Hacienda de Peñuelas': 'Aguascalientes',
'El Chichimeco': 'Aguascalientes'

    
    
    
    
    
}





# Replace the strings in the 'column_name' column
wastefinal4['City'] = wastefinal4['City'].replace(replace_city)

In [16]:
wastefinal4.reset_index(drop=True, inplace=True)

In [14]:
wastefinal4.to_excel("wastefinal4.xlsx")

In [49]:
wastefinal4 = pd.read_excel('wastefinal4.xlsx')

wastefinal4

,Index,Annual capacity,Area,Available City Data,City,Data Source,Estimated amount of included waste,Informal Sector,Status,Year,...,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
0,1,NaN,NaN,True,Jalalabad,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
1,2,NaN,NaN,True,Kandahar,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
2,3,NaN,NaN,True,Mazar-E-Sharif,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
3,4,NaN,NaN,True,Kabul,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN,NaN,25.00
4,5,NaN,NaN,True,Herat,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
5,6,NaN,NaN,True,Luanda,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,True,Korca,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,True,Vlora,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,10.00,NaN,NaN
8,9,NaN,NaN,True,Abu Dhabi,World Bank,NaN,NaN,NaN,2016,...,NaN,9.00,NaN,NaN,9.0,62.00,NaN,20.00,NaN,NaN
9,10,NaN,NaN,True,Dubai,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,75.00,NaN
10,11,NaN,NaN,True,Cordoba,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,69.32,NaN,NaN,30.00,NaN,0.68,NaN,NaN
11,12,NaN,NaN,True,Rosario,World Bank,NaN,NaN,NaN,2016,...,NaN,15.20,NaN,NaN,NaN,NaN,NaN,NaN,89.19,NaN
12,13,NaN,NaN,True,Buenos Aires,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,14.42,7.20,61.50,16.88
13,14,NaN,NaN,True,Vanadzor,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,90.00,NaN,NaN,NaN,10.00
14,15,NaN,NaN,True,Spitak,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,93.16,NaN,NaN,NaN,6.84
15,16,NaN,NaN,True,Canberra,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,28.00,NaN,NaN,NaN,NaN,70.00,NaN,2.00
16,17,NaN,NaN,True,Vienna,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,True,Baku,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,24.21,NaN,NaN,NaN,NaN,36.36,49.22
18,19,NaN,NaN,True,Muyinga,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
19,20,NaN,NaN,True,Kayanza,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,NaN,NaN,True,Ngozi,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
21,22,NaN,NaN,True,Bujumbura,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,100.00,NaN,NaN,NaN,NaN
22,23,NaN,NaN,True,Brussels,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,NaN,NaN,True,Liege,World Bank,NaN,NaN,NaN,2016,...,3.0,14.00,NaN,26.00,NaN,NaN,NaN,53.00,4.00,NaN
24,25,NaN,NaN,True,Porto Novo,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,NaN,NaN,True,Cotonou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,NaN,NaN,True,Bobo Dioulasso,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,NaN,NaN,True,Ouagadougou,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,NaN,NaN,True,Patuakhali,World Bank,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,55.45,NaN,4.55,NaN,40.00
29,30,NaN,NaN,True,Chittagong,World Bank,NaN,NaN,NaN,2016,...,NaN,0.42,NaN,NaN,NaN,29.17,NaN,12.41,NaN,58.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,992,NaN,NaN,True,Baidyabati,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
972,993,NaN,NaN,True,Bangalore,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
973,994,NaN,NaN,True,Bhaktapur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
974,995,NaN,NaN,True,Bulgan,MSW Asia Pacific,NaN,NaN,NaN,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
975,996,NaN,NaN,True,Champdani,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
976,997,NaN,NaN,True,Chittagong,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
977,998,NaN,NaN,True,Dehiwala Mount Lavinia,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,999,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
979,1001,NaN,NaN,True,Dhaka,MSW Asia Pacific,NaN,NaN,NaN,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
980,1002,NaN,NaN,True,Gujranwala,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
981,1003,NaN,NaN,True,Ho Chi Minh,MSW Asia Pacific,NaN,NaN,NaN,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
982,1005,NaN,NaN,True,Kathmandu,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,1006,NaN,NaN,True,Katunayake Seeduwa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,1007,NaN,NaN,True,Kesbewa,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,1008,NaN,NaN,True,Kirtipur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,1009,NaN,NaN,True,Kolkata,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
987,1010,NaN,NaN,True,Konnagar,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
988,1011,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989,1012,NaN,NaN,True,Kurunegala,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,1013,NaN,NaN,True,Lalitpur,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,1014,NaN,NaN,True,Lautoka market,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,1015,NaN,NaN,True,Moratuwa Municipal,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,1016,NaN,NaN,True,Nuwara Eliya,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,1017,NaN,NaN,True,Palembang,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,1018,NaN,NaN,True,Ratnapura,MSW Asia Pacific,NaN,NaN,NaN,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,1019,NaN,NaN,True,Rishra,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,1020,NaN,NaN,True,Serampore,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,1021,NaN,NaN,True,Thimi,MSW Asia Pacific,NaN,NaN,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1022,NaN,NaN,True,Trincomalee,MSW Asia Pacific,NaN,NaN,NaN,2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,1023,NaN,NaN,True,Uttarpara-Kotrung,MSW Asia Pacific,NaN,NaN,NaN,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN